### ISSUE TITLE
fix(Modal): Incorrect display location of Modal with CSS 2.3.1

### ISSUE THREAD

**Issue by mgandley** [Semantic-Org/Semantic-UI-React#2689] opened 2018-03-27 20:52 UTC
**Steps to Reproduce**
1. Use a modal.

**Expected**
The modal should be centered.

**Result**
The modal is not centered.

**Testcase**
Working: https://codepen.io/anon/pen/qopZBP
Not Working: https://codepen.io/anon/pen/qopZBP

Same code, only difference is using css 2.2.4 vs using css 2.3.1.

Not sure if this is an issue with the react library or the CSS, opening issue in both locations.

**Comment by brianespinosa** [comment] 2018-03-27 20:56
Duplicate of #2550

**Comment by mgandley** [comment] 2018-03-27 20:56
Derp.   #2250 
Beaten by seconds.  Thanks @brianespinosa.

**Closed as completed by brianespinosa** 2018-03-27 20:56 UTC
Labels: duplicate
