### ISSUE TITLE
Modal not showing properly

### ISSUE THREAD

**Issue by hieunguyendut** [Semantic-Org/Semantic-UI-React#3608] opened 2019-05-14 09:04 UTC
### Steps
The modals component open full height of the screen and It is also not displays in center.(apologise for my poor english)

### Expected Result
![Screenshot from 2019-05-14 15-57-03](https://user-images.githubusercontent.com/30219446/57684914-f58b5d00-7660-11e9-8371-8cda1e76e293.png)

### Actual Result
![Screenshot from 2019-05-14 15-57-45](https://user-images.githubusercontent.com/30219446/57685163-7e09fd80-7661-11e9-8a46-456339b5383d.png)

### Version
Google Chrome 74.0.3729.131 
![Screenshot from 2019-05-14 16-00-20](https://user-images.githubusercontent.com/30219446/57685122-6894d380-7661-11e9-9cb5-737f115cbfe9.png)

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment] 2019-05-14 10:40
As I see it's a duplicate of #3345, see https://github.com/Semantic-Org/Semantic-UI-React/issues/3345#issuecomment-452687134 for more details.

Solution: use CDN version of Semantic UI or use `semantic-ui`/`semantic-ui-less` to get latest styles.

**Closed as completed by layershifter** 2019-05-14 10:40 UTC
Labels: duplicate

**Comment by hieunguyendut** [comment] 2019-05-14 10:46
Yep. Thanks for ur response. I also tried the solution u show me above before use semantic-ui-css module 
but I still got same problem. Both issue duplication also not really helpful

**Comment by layershifter** [comment] 2019-05-14 11:01
Did you try to disable `semantic-ui-css` and use `https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css` from CDN?

If it's still persists please create a repro on CodeSandbox...

**Comment by hieunguyendut** [comment] 2019-05-15 01:47
I tried to simulate error on CodeSandbox by use the same module(react react-dom semantic-ui-react..) on CodeSanbox but It can't produce error on it. I will try to figure it out and simulate on CodeSanbox and show you.

**Comment by hieunguyendut** [comment] 2019-05-15 02:10
Btw, when I create new project to test It worked perfectly

**Comment by sistemaswebbrasil** [comment] 2019-06-28 14:05
I have the same problem as the colleague, I used the cdn indicated but the problem persists.

**Comment by sistemaswebbrasil** [comment] 2019-06-28 15:05
I was having the same problem, after creating a new project that I realized the problem was an example css login screen, the Modal is working perfectly.
