### ISSUE TITLE
Modal error when open in Safari

### ISSUE THREAD

**Issue by namcoder** [Semantic-Org/Semantic-UI-React#2889] opened 2018-06-07 09:59 UTC
Hi. I have tested in Chrome and Safari. In Chrome the Modal works fine but got error in Safari.
![screen shot 2018-06-07 at 4 55 40 pm](https://user-images.githubusercontent.com/8687083/41092838-fe65583a-6a73-11e8-86d5-ae3024bc9d96.png)

Error appear when the "open" attribute is true . I also tested in https://react.semantic-ui.com/modules/modal

Please take a look. Thank you

**Comment by layershifter** [comment] 2018-06-07 10:59
Looks like duplicate of #2886.

**Closed as completed by layershifter** 2018-06-07 10:59 UTC
Labels: duplicate
