### ISSUE TITLE
Theming incompatibility with react-scripts v5.  TypeError: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by AmirHMousavi** [Semantic-Org/Semantic-UI-React#4310] opened 2021-12-21 16:37 UTC
## Bug Report

Enable theming for `semantic-ui-react` throws error on starting the project

### Steps
Freshly create a new project with CRA v5 `npx create-react-app myapp --template typescript`

the installed packages will be:

```sh
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "typescript": "^4.5.4",
```
Follow the instruction for enable themeing 

```
yarn add semantic-ui-react
yarn add @craco/craco @semantic-ui-react/craco-less semantic-ui-less --dev

# replace `react-scripts` commands with `craco` 
# and the rest of configurations

```
### Expected Result
`yarn start `should run the project in dev mode

### Actual Result

```
❯ yarn start
/repoPath/node_modules/@semantic-ui-react/craco-less/dist-node/index.js:91
  fileLoaderMatch.loader.exclude.push(/theme.config$/);
                                 ^

TypeError: Cannot read properties of undefined (reading 'push')
    at Object.overrideWebpackConfig (/repoPath/node_modules/@semantic-ui-react/craco-less/dist-node/index.js:91:34)
    at overrideWebpack (/repoPath/node_modules/@craco/craco/lib/features/plugins.js:42:40)
    at /repoPath/node_modules/@craco/craco/lib/features/plugins.js:64:29
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (/repoPath/node_modules/@craco/craco/lib/features/plugins.js:63:29)
    at mergeWebpackConfig (/repoPath/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:110:30)
    at overrideWebpackDev (/repoPath/node_modules/@craco/craco/lib/features/webpack/override.js:11:36)
    at /repoPath/node_modules/@craco/craco/scripts/start.js:27:5

Node.js v17.3.0
```

### Version
dependencies
`    "semantic-ui-react": "^2.0.4",`

devDependencies
```sh
    "@craco/craco": "^6.4.3",
    "@semantic-ui-react/craco-less": "^1.2.3",
     "semantic-ui-less": "^2.4.1"
```

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment] 2022-01-03 20:27
Duplicate of #4301.

**Closed as completed by layershifter** 2022-01-03 20:27 UTC
Labels: duplicate

**Comment by layershifter** [comment] 2022-01-13 16:07
> @semantic-ui-react/craco-less@2 with support of Craco 6 is published. I tested in on a small project and it works.

https://github.com/Semantic-Org/Semantic-UI-React/issues/4301#issuecomment-1012278916
