### ISSUE TITLE
Delay when rendering icons such as "right arrow" or "right chevron" on the mobile

### ISSUE THREAD

**Issue by erickrojasfigueroa** [Semantic-Org/Semantic-UI-React#2339] opened 2017-11-23 07:20 UTC
### Steps

1. Create icon component with an icon with a separate name, for example:

```
<Icon name='right arrow' />
<Icon name='right chevron' />

```

### Expected Result

1. Render quickly and have no conflict with the rest of the component

### Actual Result

1. when manipulating other elements in the same component it takes time to render.

1. Has a rendering delay of 1s to 1.5s

### Version
"semantic-ui-react": "^0.76.0"

**Comment by layershifter** [comment] 2017-11-23 07:30
Looks like duplicate of #2301, please post more details if it's another problem.

**Closed as completed by layershifter** 2017-11-23 07:30 UTC
Labels: duplicate
