### ISSUE TITLE
Dropdown menu errors out when navigating with keyboard

### ISSUE THREAD

**Issue by cheng-tan** [Semantic-Org/Semantic-UI-React#958] opened 2016-11-29 21:55 UTC
### Steps
1. Use the dropdown with `Dropdown.Menu` and `Dropdown.Item`. For example: http://react.semantic-ui.com/modules/dropdown#search-in-menu

2. Click on the `Search In-Menu` dropdown to open it.

3. Press down arrow on the keyboard, then it errors out.
The error message in the console is: `app.61ca82f….js:6621 Uncaught TypeError: Cannot read property 'length' of undefined`

### Expected Result
User should be able to navigate through the dropdown using up and down arrow.

### Actual Result
It throws errors if the dropdown is created with `Dropdown.Menu` and `Dropdown.Item`

### Version
0.61.7

**Comment by levithomason** [comment] 2016-11-30 18:21
Per the info message on the example:

>The example below shows the desired markup but is not functional. Needs to be defined via shorthand, which is not yet possible.
>If there's no pull request open for this, you should contribute!

This is not a bug but a missing feature, PRs welcome.

**Comment by levithomason** [comment] 2016-11-30 18:22
Closing as a dupe of #889

**Closed as completed by levithomason** 2016-11-30 18:22 UTC
Labels: duplicate
