### ISSUE TITLE
fix(Modal): Including onClose gives an error

### ISSUE THREAD

**Issue by jlag34** [Semantic-Org/Semantic-UI-React#643] opened 2016-10-07 20:00 UTC
**Steps to Reproduce**
Copy and paste a modal and include onClose in the `<Modal>` tag

**Expected**
No error

**Result**
Unknown prop `onClose` on `<div>` tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop. In div (created by Modal)

I looked more into this and it lead me to:

https://github.com/react-bootstrap/react-bootstrap/issues/1994

which lead me to:

https://github.com/facebook/react/pull/6800

Sorry if you guys are already aware of this. Poked around a bit and didn't see anyone bring this up yet.

**Comment by levithomason** [comment] 2016-10-08 00:59
I suspect this is due to an older version.  We recently updated the Modal from `onHide` to `onClose`.  Though, the latest master does not throw this warning, neither do the latest docs for the Modal with `onClose`: http://localhost:8080/modules/modal#close-config

Our components "consume" props that they handle, and pass the rest on the underlying element.  If you're on a version where the Modal does not handle and consume the `onClose` prop, then it will pass it to the `div` and cause this error.

Closing as I cannot reproduce on the latest.  Feel offer more info if you see the error after updating.

**Closed as completed by levithomason** 2016-10-08 00:59 UTC
Labels: invalid
