### ISSUE TITLE
Popup message stuck on hover event

### ISSUE THREAD

**Issue by yuhong-l** [Semantic-Org/Semantic-UI-React#3296] opened 2018-11-22 15:16 UTC
## Bug Report
When using the popup functionality on a button connected with a click event the popup sometimes creates a div but it won't remove it when hovering out of the button so when hovering again, another div will show on top of the current one.

### Expected Result
popup should disspear after mouse move out of the button/popup
### Actual Result
The popup content remains unchanged, like stuck there.💣

### Version
    "semantic-ui-react": "0.83.0",

### Testcase
As below pic, it's obviously my mouse move out of the Popup box, but the Popup didn't appear.
![image](https://user-images.githubusercontent.com/37088436/48910984-6caf1800-eeac-11e8-9295-00b982b33020.png)

I use the Popup component as below.
 <Popup
                ...
                onClose={this.onclose}
                 trigger={<MyButton>}
            />

The experiment result is: 
If I hover my mouse on the Popup element, then it pop up 'words' as expected.
After that if I click the Button to trigger something, and **slowly(or in normal speed)** move my mouse out of the Popup element, the hovering 'words' will disappear as expected.

However, 
If I hover my mouse on the Popup element, then it pop up 'words' as expected.
After that if I click the Button to trigger something, and move my mouse out of the Popup element **fast enough**, the hovering 'words' will not disappear but keep showing as my mouse is still hovoring on it.

Update:
For better description, 
I specially add a callback function this.onclose for props:   onClose?: (event: React.MouseEvent<HTMLElement>, data: PopupProps) => void
**To test whether the onClose() event is triggered.**
In my experiment result, 
the onClose() is triggered in the **first case(slow move out)** as expected, but **not** triggered in the **second case(move out fast).**

**Comment by layershifter** [comment] 2018-12-10 08:46
This can be a duplicate of #3257, can you try the latest release?

Can please make a minimal repro case on codesandbox and add clear steps to reproduce?

**Closed as completed** 2018-12-28 09:25 UTC
Labels: needs author feedback
