### ISSUE TITLE
Popup: Incorrect arrow position on flowing popup

### ISSUE THREAD

**Issue by peperoni321** [Semantic-Org/Semantic-UI-React#3790] opened 2019-09-23 08:22 UTC
## Bug Report
When popup is flowing and its width exceed x-axis position of triggered component then the arrow is incorrectly placed.

### Steps
Add flowing attribute to the popup component and set its width greater then position of triggered component on x axis

### Expected Result
In version 0.81.1 which I'm still using this problem not exists so the arrow is placed correctly above triggered component

### Actual Result
In the latest version arrow is not placed above/below the triggered component but in quite different place

### Version
0.88.1

### Testcase
https://codesandbox.io/s/z5le7?module=/example.js

**Comment by layershifter** [comment] 2019-09-23 09:57
Closing this as duplicate of #3771, the issue is the same in fact. Opened for ideas and PRs there 🙏

**Closed as completed by layershifter** 2019-09-23 09:57 UTC
Labels: duplicate
