### ISSUE TITLE
Warning: Failed prop type: Invalid prop `name` of value `redo` supplied to `Icon`.

### ISSUE THREAD

**Issue by sushi-udon** [Semantic-Org/Semantic-UI-React#4295] opened 2021-10-12 04:50 UTC
## Bug Report
I want to use `redo` icon at `<Dropdown.Item>`.
But it output error.
What should I do?

### Steps
```
<Dropdown.Menu>
  <Dropdown.Item icon="redo" />
</Dropdown.Menu>
```

![スクリーンショット 2021-10-12 13 45 08](https://user-images.githubusercontent.com/61356332/136892862-293cd492-c3e2-44ae-bf00-6003d2630b30.png)

A clear and concise description of steps to reproduce the problem.

**Comment by brianespinosa** [comment] 2021-10-14 18:56
@sushi-udon please complete the entire bug report. We need to know the version you are using. It is most likely that you are using a version that does not have that icon included. We include a codesandbox link in our bug report form to make it as easy as possible to show us what you are experiencing. I am guessing the issue is not using the latest SUIR.

Closing this issue but we can reopen if all of the required bug report info is given with a reproduction case.

**Closed as completed by brianespinosa** 2021-10-14 18:56 UTC
Labels: needs author feedback
