### ISSUE TITLE
Accordion open/close state is persisted when it's not suppose to be.

### ISSUE THREAD

**Issue by darewreck54** [Semantic-Org/Semantic-UI-React#2184] opened 2017-10-10 20:19 UTC
Accordion doesn't reinitialize the state of whether it's open or not.  Whenever there is an update to the props that are passed into the accordion, whether it's open or not is not reset. As a result, it's persisted.

I used Tabs as an example of a way to switch different contents in the accordion.   Imagine you have a component that uses accordion to display content.  If the component updates it's data and want to display a new accordion, this problem will occur

### Steps
https://codepen.io/darewreckk/pen/VMxJoP?editors=1111
1) In Tab 1, close all the accordion
2) Switch to Tab2, notice that the accordion is close.  Open the accordion.  
3) Switch to Tab1, notice that the accordion is open.  Before it was closed.  

### Expected Result
I would expect that the accordion state (whether its open or not) is not persisted between the tabs.

### Actual Result
Whether the accordion is open or not is persisted to the other tabs.

### Version
2.2.4

### Testcase
https://codepen.io/darewreckk/pen/VMxJoP?editors=1111

**Comment by layershifter** [comment] 2017-10-11 18:07
You should use `renderActiveOnly={false}` and `pane` instead of `render()`, [codepen](https://codepen.io/layershifter/pen/vervKm?editors=0010).

However, current behaviour with `render()` is very confusing that's why I've created #2181. It will make the behaviour in the codepen default.

**Comment by darewreck54** [comment] 2017-10-11 21:02
@layershifter 

How do you address the issue if your using an accordion only and not using Tabs?  In my code, I'm not using the tab component to trigger the switching between panels.  I'm just updating data and rerendering the accordion.  How would you apply the address this problem if you were were just using Accordions and just updating the data passed in.  

This is actually referencing the older version before the accordion breaking change update

Here is an example:
https://codepen.io/darewreckk/pen/pWKXNd?editors=1111

**Comment by layershifter** [comment] 2017-10-12 17:12
@darewreck54 Make your `Accordion` controlled and pass `activeIndex` prop, [example](https://react.semantic-ui.com/modules/accordion#accordion-example-active-index). In fact it's an expected behaviour because the component works with indexes.

**Comment by layershifter** [comment] 2017-10-14 14:16
Closing this as the described issue with `Tab` is duplicate.

**Closed as completed by layershifter** 2017-10-14 14:16 UTC
Labels: duplicate

**Comment by darewreck54** [comment] 2017-10-17 19:46
@layershifter 

https://codepen.io/darewreckk/pen/mBaeLQ?editors=1111  I've updated the code to use the current library.

However, I'm still seeing the issue with the accordion active state persisting.  In the example, I have exclusive set to false so user can open multiple accordions.  I pass in panels, and when you press toggle it changes the panels that are being shown.  If you open up level 2 and click on toggle data, you will see level 43 automatically open; which is a persistent state from the first trigger.  

is there something similar to   renderActiveOnly={false} for accordion?

It's not clear how you would manage the active index of each accordion if they are not exclusive.  When they are exclusive, you can just reset the active index to be -1.  However, this isn't true at the Accordion.Accordion level.


I actually found a workaround but managing a state of each accordion.

https://codepen.io/darewreckk/pen/oGJBvZ?editors=1111

It would be nice if accordion.accordion gave you the ability to do something similar unless there is some other way that I couldn't figure out.  

Thanks,
Derek

I can open another issue on this since this is closed.  Let me know how to proceed.

**Comment by layershifter** [comment] 2017-10-18 17:22
There is no bug or issue actually. `Accordion` and `Accordion.Accordion` work with indexes so it's correct that they keep their state when you are changing the `panels` prop.

I don't see the problem there. Give name to your `panels` groups and keep index for each other. Keep in mind, that `Accordion` uses array for indexes when `exclusive={false}`. [Codepen](https://codepen.io/layershifter/pen/WZLVGQ?editors=0010), quite dirty, but shows the idea.

**Comment by darewreck54** [comment] 2017-10-19 20:26
@layershifter if the panels are changing, wouldn't that mean that this should be accounted for in the state as well since the panel is the main data source for the accordion.  In otherwords, if the accordion is built off the panel data, and the data gets updated shouldn't the accordion reflect that and reset the state to the default?

Trying to think of what use case that would be desirable with keeping the state when panels is being updated
