### ISSUE TITLE
Setting a grid to be stackable has no effect in mobile browsers

### ISSUE THREAD

**Issue by jeremyadell** [Semantic-Org/Semantic-UI-React#1815] opened 2017-06-30 00:53 UTC
✔ BUGS → This form is required:
Sorry for the lack of a test case, but I was unable to get codepen to load a grid.

### Steps
Create a grid as 
<Grid  stackable columns={2}>
</Grid>
Add in two columns

Override the theme's min-width...
body {
  min-width: 10px !important; 
}

When shrinking the browser window on a desktop, the columns stack on top of each other fine

Issue is when you open the page in a mobile browser or by using Chrome's mobile browser emulator

### Expected Result
Columns should stack on top of each other

### Actual Result
Columns do not stack

### Version
0.70.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment] 2017-06-30 06:50
Seems, it's duplicate of #1538.

**Closed as completed by layershifter** 2017-06-30 06:50 UTC
Labels: question
