### ISSUE TITLE
CSS !important statement overwrites Modal behaviour and pushes in corner

### ISSUE THREAD

**Issue by notflip** [Semantic-Org/Semantic-UI-React#2795] opened 2018-05-14 13:57 UTC
### Steps
Just created a Modal element (from the example page)

### Expected Result
<img width="772" alt="screen shot 2018-05-14 at 21 56 05" src="https://user-images.githubusercontent.com/4146384/40001820-a3ccb072-57c1-11e8-8f65-3fdb50756c3b.png">

<img width="240" alt="screen shot 2018-05-14 at 21 56 29" src="https://user-images.githubusercontent.com/4146384/40001836-ae7cb148-57c1-11e8-923a-dcd2f77aa01f.png">

### Actual Result
<img width="799" alt="screen shot 2018-05-14 at 21 54 52" src="https://user-images.githubusercontent.com/4146384/40001856-b53e1fee-57c1-11e8-85ad-0a659b9e057e.png">

<img width="236" alt="screen shot 2018-05-14 at 21 57 11" src="https://user-images.githubusercontent.com/4146384/40001894-c73cea54-57c1-11e8-88b9-d570eea5d6e0.png">

### Version
Latest

**Comment by layershifter** [comment] 2018-05-14 15:15
Duplicate of #2550 as I see.

**Closed as completed by layershifter** 2018-05-14 15:15 UTC
Labels: duplicate
