### ISSUE TITLE
Dropdown code sandbox not working

### ISSUE THREAD

**Issue by mattnedrich** [Semantic-Org/Semantic-UI-React#3479] opened 2019-03-07 16:22 UTC
### Steps
1. Visit https://react.semantic-ui.com/modules/dropdown/
2. Select "Code Sandbox" for the "Selection" or "Search Selection" variants

### Expected Result
It allows you to open a code sandbox for the dropdown component

### Actual Result
Progress indicator displayed and never finishes

**Comment by Fabianopb** [comment] 2019-03-09 13:55
Just checked at the current master, bug confirmed, I'll take a look soon!

**Comment by layershifter** [comment] 2019-03-10 09:34
It's caused by some internal imports like this:
```js
import { friendOptions } from '../common'
```

This code is not uploaded to CodeSandbox 🤔

**Comment by layershifter** [comment] 2019-03-10 11:33
@Fabianopb I've updated some components in #3486, feel free to update `Search` component's docs 👍

**Comment by Fabianopb** [comment] 2019-03-11 19:01
Sounds good, I'll work on that!

**Comment by Fabianopb** [comment] 2019-03-13 06:52
#3486 and #3494 merged, should we close the issue?

**Comment by layershifter** [comment] 2019-03-17 14:10
Removed some imports in #3511 (`ComponentExampleRenderSource.js`), @Fabianopb thanks for your work there 👍

**Closed as completed by layershifter** 2019-03-17 14:10 UTC
Labels: bug
