### ISSUE TITLE
Modal is not displayed properly

### ISSUE THREAD

**Issue by Blapi** [Semantic-Org/Semantic-UI-React#3289] opened 2018-11-20 09:34 UTC
## Bug Report
When upgrading to the latest version of Semantic UI React, all the Modals I have in my app are now kind of broken.
The "fullscreen" modal in scrolling mode is now located at the bottom of the screen and flickers (when looking in the console, I saw that the class was switching between scrolling and not scrolling).
The other modals are not centered anymore and they go on the bottom right of my screen (because of a style in semantic css which does `top: 50%; left: 50%`

In order to make it work properly again, I had to check in the previous version what was different and I saw that in the latest version, `position: static !important` was missing in the new style.

So I added this property in my css and everything went back as expected, my Modals were not broken anymore.

I just want to know if I missed a part, or if there was a better practice to fix it ?

I read all the existing issues, and except from this one https://github.com/Semantic-Org/Semantic-UI-React/issues/2221#issuecomment-374822317 which helped me on the flicker issue, all the other issues were closed and marked as duplicated without providing a proper solution to the Modal issue.

### Version
    "semantic-ui-css": "2.4.1"
    "semantic-ui-react": "0.83.0"

**Comment by layershifter** [comment] 2018-11-20 10:33
There is an issue with incorrect padding for the `fullscreen` size in Semantic UI 2.4.0, it is also reproducing in docs. It was fixed in 2.4.1, [RELEASE-NOTES.md](https://github.com/Semantic-Org/Semantic-UI/blob/master/RELEASE-NOTES.md#version-241---oct-13-2018). However, our docs are running on 2.4.0, yet.

The other weird thing that [semantic-ui-css@2.4.1](https://cdn.jsdelivr.net/npm/semantic-ui-css@2.4.1/semantic.min.css) still points to 2.4.0.

<details>
  <summary>Preview of issue</summary>

![image](https://user-images.githubusercontent.com/14183168/48766297-cc46d100-ecbc-11e8-8b8a-46cd39bc0c8b.png)
</details>

----

`top: 50%; left: 50%` is applied only for `.legacy` modals as I see, https://github.com/Semantic-Org/UI-Modal/blob/master/modal.css#L326. We don't use this feature, yet.

However, as I see this issue is still duplicate of #2221, I'm correct? Because it caused by conditionally apply of `scrolling` CSS class. We don't have any valid solution or a fix for this, feel free to open PR that will make our calculations there correct and predictable.

**Comment by layershifter** [comment] 2018-11-25 09:31
Closing as duplicate, PRs are welcome 👍

**Closed as completed by layershifter** 2018-11-25 09:31 UTC
Labels: duplicate
