### ISSUE TITLE
IE11 long modal scrolling

### ISSUE THREAD

**Issue by sergez** [Semantic-Org/Semantic-UI-React#1759] opened 2017-06-10 20:12 UTC
`dimmed` isn't assigned/added to body when opening long modal in IE11

### Steps
- Open long modal in IE11

### Expected Result
The modal should be scrollable
<body class="dimmable dimmed scrolling">

### Actual Result
The modal isn't scrollable
<body class="dimmable scrolling">

### Version
0.68.5

### Testcase
Open in IE11 https://codepen.io/anon/pen/gRrPRo

**Comment by marcdibold** [comment] 2017-06-12 07:12
duplicate? https://github.com/Semantic-Org/Semantic-UI-React/issues/1157

**Comment by layershifter** [comment] 2017-06-12 07:13
Yep, it's dupe of #1157.

**Comment by sergez** [comment] 2017-06-12 07:14
I'm not sure. Because it's reproduced with one modal and only on IE11

**Comment by sergez** [comment] 2017-06-12 07:19
c'mon guys. It not duplicate. However #1157 reproduced in every browser and this bug reproduced only in IE11. Have you tried to open ONLY ONE long modal in Chrome and in IE11 ?

**Comment by sergez** [comment] 2017-06-12 07:21
I used link to codepen from #1157 to keep it alive. It might confuse you...

**Comment by layershifter** [comment] 2017-06-12 08:58
@sergez You're right, thanks for clarification. I've checked in IE and there is really something wrong.

### Chrome

![_885](https://user-images.githubusercontent.com/14183168/27026330-09d02986-4f66-11e7-90fa-5db82bf76039.png)

### IE

![_886](https://user-images.githubusercontent.com/14183168/27026338-0d5f464a-4f66-11e7-8bfe-c6347611d830.png)

**Comment by levithomason** [comment] 2017-06-15 03:48
We can leave this open for investigation, but highly likely that this is a CSS issue which should be fixed over at https://github.com/Semantic-Org/Semantic-UI.

**Comment by zlove** [comment] 2017-07-13 05:00
The problem is probably that [IE11 does not support multiple parameters in classList.add()](http://caniuse.com/#feat=classlist), so the 'dimmed' class is not being added to the body element. 

See [handlePortalMount() in Modal.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Modal/Modal.js#L195)

```javascript
handlePortalMount = (e) => {
    debug('handlePortalMount()')
    const { dimmer } = this.props
    const mountNode = this.getMountNode()

    if (dimmer) {
      debug('adding dimmer')
      
      // FIXME - needs workaround to work in IE 11?
      mountNode.classList.add('dimmable', 'dimmed')

      if (dimmer === 'blurring') {
        debug('adding blurred dimmer')
        mountNode.classList.add('blurring')
      }
    }

    this.setPosition()

    const { onMount } = this.props
    if (onMount) onMount(e, this.props)
  }
```

**Comment by zlove** [comment] 2017-07-13 07:38
Using a classList polyfill (https://github.com/yola/classlist-polyfill) resolved this issue for me.

**Comment by layershifter** [comment] 2017-07-13 09:38
@zlove thanks for the investigation :+1: PR is coming

**Comment by zlove** [comment] 2017-07-13 17:22
Happy to help @layershifter. Thanks for the quick fix!

**Closed as completed** 2017-07-16 21:34 UTC
Labels: bug

**Comment by mgandley** [comment] 2018-05-17 19:33
This is an issue again.  The testcase in the original issue report still applies in IE11.  Opening the modal does not apply classes `dimmable` `dimmed ` or `scrolling`.  Cannot scroll in the resulting modal.
