### ISSUE TITLE
Create Semantic UI Card Component

### ISSUE THREAD

**Issue by athurman** [Semantic-Org/Semantic-UI-React#146] opened 2016-01-20 18:37 UTC
Need a stardust component for this semantic ui view: http://semantic-ui.com/views/card.html

**Comment by levithomason** [comment] 2016-03-16 06:19
I've gone through and added a list of [supported components](https://github.com/TechnologyAdvice/stardust#support).  In doing so, I've also added issues for every missing component. Closing this one as a duplicate of #186

**Closed as completed by levithomason** 2016-03-16 06:19 UTC
