### ISSUE TITLE
Modal flickers resizing when modal content is larger than page

### ISSUE THREAD

**Issue by Jazzepi** [Semantic-Org/Semantic-UI-React#3197] opened 2018-10-05 21:58 UTC
## Bug Report
AFAIK this is NOT the bug where the size of the modal is "close" to the size of the window causing the modal to flip back and forth between scrolling and not scrolling. The modal in this example is very large. Instead, this appears to be an issue related to the size of the height as measured by https://github.com/Semantic-Org/Semantic-UI-React/blob/0b34d9bbff37e3cbbeff79fee99c4c0de848f475/src/modules/Modal/Modal.js#L249

When the modal is open it continuously calls setPositionAndClassNames() but every other time the height that comes back from the height measuring function does not respect the contents of the modal. I was able to hack around this by applying the following "fix" so that the height measurement would be consistent.

```
<Modal open={this.state.showEmailModal} onClose={() => {this.setState({showEmailModal: false})}} style={{height: 'fit-content'}}>
    <Modal.Content>
        <Header size={'huge'}>This is just a placeholder to show you what kind of email would show up in the candidate's inbox. The email look and feel will be completely configurable so that it bears your company's logos, watermarks, and styling.</Header>
        <Image src={emailTemplate}/>
    </Modal.Content>
</Modal>
```
Here's what the HTML looks like for the modal after the fix. The height fit content forces the height returned by the javascript to be consistent with what's actually inside of the modal.

```
<div class="ui scrolling modal transition visible active" style="height: fit-content;">
    <div class="content">
        <div class="ui huge header">This is just a placeholder to show you what kind of email would show up in the candidate's inbox. The email look and feel will be completely configurable so that it bears your company's logos, watermarks, and styling.</div>
        <img src="/ec45c3bbacf1cf90464a6736119c7a2b.png" class="ui image">
    </div>
</div>
```

### Steps
1. Create a modal who's content is significantly taller than your screen. I had an image in mine, but I was able to reproduce it with a bunch of text.
2. Open the modal (button, or defaultOpen=true both work).
3. See the modal thrashing on your screen.

```
<Modal open={this.state.showEmailModal} onClose={() => {this.setState({showEmailModal: false})}}>
    <Modal.Content>
        <Header size={'huge'}>This is just a placeholder to show you what kind of email would show up in the candidate's inbox. The email look and feel will be completely configurable so that it bears your company's logos, watermarks, and styling.</Header>
        <Image src={emailTemplate}/>
    </Modal.Content>
</Modal>
```

I can't replicate this outside of my own build (I tried using the hosted version found here -> http://react.semantic-ui.com/modules/modal/#modal-example-dimmer).

### Expected Result
The modal to not thrash on my screen.

### Actual Result
The modal thrashes on my screen.

### Version
The bug was introduced in the 0.81.1 release. Here's my exploration bisecting the problem.

0.82.5 - BAD
0.82.4
0.82.3
0.82.2
0.82.1
0.82.0
0.81.3 - BAD
0.81.2
0.81.1 - BAD
0.80.2 - OK
0.80.0
0.79.1 - OK

### Testcase
[Fork, update, and replace this pen to show the bug]:
This is not failing in the hosted environment. I have a feeling its because of the environment. If you pull it down locally and run it I think you'll see the problem. I stripped my react app was literally just rendering the modal and nothing else and it was blowing up. I've included a link to a codesandbox that does not show the problem happening, but should give you a sample app to test on.

https://codesandbox.io/s/w818wv4p8

**Comment by layershifter** [comment] 2018-10-07 07:39
It looks like a duplicate of #2221. Please correct me if I'm wrong.

Thank you for the detailed description, possible you can be fix it and will make a PR? :cat:

**Closed as completed by layershifter** 2018-10-07 07:39 UTC
Labels: duplicate
