### ISSUE TITLE
https://react.semantic-ui.com/ website not working

### ISSUE THREAD

**Issue by ghanavel** [Semantic-Org/Semantic-UI-React#4283] opened 2021-09-06 03:35 UTC
https://react.semantic-ui.com/ website not working, seems down.

182.79.218.34 refused to connect.

**Comment by sholladay** [comment] 2021-09-06 20:50
Working for me.

**Comment by layershifter** [comment] 2021-09-20 11:28
Duplicate of #4285.

**Closed as completed by layershifter** 2021-09-20 11:28 UTC
Labels: duplicate
