### ISSUE TITLE
Dropdown: module scrollbar can not work as normal in firefox browser

### ISSUE THREAD

**Issue by ypxu87** [Semantic-Org/Semantic-UI-React#2459] opened 2018-01-24 03:19 UTC
✔ BUGS → This form is required:

### Steps
1.put the Dropdown module in Long Modal 
2.test in **firefox** browser,drag the Dropdown scrollbar.

### Expected Result
It can scroll when drag the scrollbar
### Actual Result
Test in **firefox** browser,drag the Dropdown scrollbar but it does not work
### Version
0.77.1

**Comment by brianespinosa** [comment] 2018-01-24 18:12
@ypxu87 please provide a Codesandbox example of your issue. We can't tell if your problem is CSS or JS based without having anything to look at.

**Comment by ypxu87** [comment] 2018-01-26 03:40
@brianespinosa please use **firefox** browser to check it: https://codesandbox.io/s/73zvlnqv86

**Comment by brianespinosa** [comment] 2018-01-26 06:17
Thanks for providing a codesandbox example, @ypxu87. I just tested your codesandbox and I am able to take my cursor, place it on the scrollbar, and drag. I did not use a scrollwheel or scroll gesture. I tested on macOS on the latest version of Firefox (57.0.1).

I am going to close this issue as I cannot reproduce. We can reopen this if I am misunderstanding your report.

**Comment by ypxu87** [comment] 2018-01-26 08:01
@brianespinosa Please check this video for detail,Thanks
https://www.screencast.com/t/XbXu8Kupx

also can not work as normal tested on macOS on the latest version of Firefox (57.0.1).

**Comment by brianespinosa** [comment] 2018-01-26 15:34
Thank you for the screencast, @ypxu87. It looks like this is indeed a valid issue. It's the scrollbar INSIDE the dropdown when rendered in a modal. I am actually seeing a different and also invalid behavior on my machine.

Based on your screencast I want to ask: Do you have a mouse connected to your computer? Usually scrollbars are only persistent like that when a mouse is connected.

On macOS when trying to click the scrollbar, it makes the scroll jump to the bottom of the viewport. I need to put a test together using out of the box SUI only and see if this is consistent there. It is possible this might be partly an issue with the scrollbar customization that was added in the last update. It also may be that we need to handle click events different in SUIR.

**Comment by brianespinosa** [comment] 2018-01-26 16:01
Adding this revised codesandbox with a description of the issue inside and cleaned out some of the extra code and proptype errors that were not needed to show the problem. https://codesandbox.io/s/ymz32qw8xv

**Comment by ypxu87** [comment] 2018-02-01 03:39
@brianespinosa hello，when this problem will be fixed?
Thanks

**Comment by brianespinosa** [comment] 2018-02-01 17:04
@ypxu87 
> Based on your screencast I want to ask: Do you have a mouse connected to your computer? Usually scrollbars are only persistent like that when a mouse is connected.

**Comment by levithomason** [comment] 2018-02-02 04:59
Note, our codebase does not include logic for scrollbars nor for scrolling.  This will be a CSS and/or browser issue at the end of the day.  Both of which are beyond the scope of the Semantic UI React repo.

**Comment by levithomason** [comment] 2018-02-02 05:02
Just to confirm, this is not an issue in FireFox ESR (extended support release):

![image](https://user-images.githubusercontent.com/5067638/35717320-5b9ff5c6-0793-11e8-91b2-3f48aeab278f.png)

![http://g.recordit.co/wdNyXIZYf1.gif](http://g.recordit.co/wdNyXIZYf1.gif)

It seems the reported issue is a FireFox bug.  Closing since it is beyond our control.

**Closed as completed by levithomason** 2018-02-02 05:02 UTC

**Comment by eug48** [comment] 2018-02-07 06:33
Yep, this is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1429373
It's fixed in Firefox 59 which is due for release on March 13.

**Comment by ypxu87** [comment] 2018-02-07 13:07
Thank you
