### ISSUE TITLE
Space trigger dropdown visibility on inputs. Perhaps an option to disable `openOnSpace`

### ISSUE THREAD

**Issue by gencer** [Semantic-Org/Semantic-UI-React#3768] opened 2019-08-31 00:14 UTC
### Steps
1. Create a dropdown
2. Give trigger an input field. Add some menu items to dropdown.
3. Click on input, you will see dropdown menu with items
4. Now write something to input. It's all ok.
5. Now try to press spacebar inside the input. Instead of adding a space to the text, it close or open dropdown.

### Expected Result
I should be able to use space in input and not trigger menu visibility

At least, we need a prop for this specific usage.

See related issue here: https://github.com/Semantic-Org/Semantic-UI-React/issues/3146

See related code here: https://github.com/Semantic-Org/Semantic-UI-React/blob/81d3cd109f54590d63d0cf54e36e63b22cd5e856/src/modules/Dropdown/Dropdown.js#L530-L535

To fix here, I commented `e.preventDefault();` as ` // e.preventDefault();`.

In fact, i can't even press space when dropdown menu is visible. Needs to be closed first. To be able to fix that, I had to remove spacebar keycode check condition from here:

https://github.com/Semantic-Org/Semantic-UI-React/blob/81d3cd109f54590d63d0cf54e36e63b22cd5e856/src/modules/Dropdown/Dropdown.js#L585-L587

Also to achieve expected result; I had to set `closeOnChange` to `false`.

For now, I monkey-patched via `patch-package`.
### Actual Result
dropdown close and open on each spacebar press

### Version
0.88.0

**Comment by layershifter** [comment] 2019-09-02 13:12
Thank for reporting. It's a bug 😿 

Duplicate of #3764, will be fixed by #3766 and released during this week.

**Closed as completed by layershifter** 2019-09-02 13:12 UTC
Labels: duplicate

**Comment by gencer** [comment] 2019-09-02 13:33
@layershifter, you underatand wrong (_or i got it wrong_).

The issue there is about when `search` prop is `true`. Meaning, dropdown has search bar on top of it. This is fixed, yes. But my use case is different. I gave input field as a trigger. I do not have `search` prop.

For example;

```
<Dropdown trigger={<Input onChange={this.onTextChange} />} fluid>

   ... menu items ...

</Dropdown>
```

Now when I press `spacekey` on `<Input />` which is a trigger of dropdown, it opens/close dropdown menu. So, I think we explicitly need `closeOnSpace` prop here.

If I put `search`, does SemanticUI adds any search bar? Or is it just a common prop for such case? In this case, I would have 2 inputs. One is from tirgger, one from dropdown  menu. I cannot test this because its not released yet.

**Comment by layershifter** [comment] 2019-09-02 13:39
Please provide a minimal repro case, it will be easier to understand the issue.

**Comment by gencer** [comment] 2019-09-02 13:45
Sure. You're right actually. 

It's on the way. Once finished, gonna publish here

**Comment by gencer** [comment] 2019-09-02 14:10
@layershifter here you go:

https://codesandbox.io/s/semantic-ui-react-e0cj6

Try to write words separated by space. Instead of adding space to input, it will either close or open dropdown and no space will be inserted.

As I said, I use input as a trigger. You can see that in code.

**Comment by layershifter** [comment] 2019-09-02 14:30
Thanks 👍  It's the same bug as in #3764.

`0.87.3`: https://codesandbox.io/s/semantic-ui-react-toyjb
`0.88.0`: https://codesandbox.io/s/semantic-ui-react-wnu42

***

However, the fix that was introduced in #3766 will not fix this issue. Okay, the next questions.

Why you need to have `Input` as `trigger` and Children API at all?
Are there reasons why you can't use `selection` & `search`: https://react.semantic-ui.com/modules/dropdown/#types-search-selection?

**Comment by gencer** [comment] 2019-09-02 14:59
I do not filter things. The `search` feature in Dropdown filters items by search `value`. My intention is completely different. I do not want to filter things, i do not want to select based on value. My intention is to provide suggestions on my own.

Live action:

![4](https://user-images.githubusercontent.com/1711576/64122832-57f0a080-cdab-11e9-854e-52b0cd8d96b2.gif)

As you can see i can put `space` as i already patched myself.

**Comment by layershifter** [comment] 2019-09-02 15:22
> I do not filter things. The `search` feature in Dropdown filters items by search `value`.

You can do this by `noop` `search` function: https://codesandbox.io/s/semantic-ui-example-6213c
This option is also more accessible.

***

And now I see that your issue is closer to #3146. As now we improved focus handling, probably we can try to bind event listeners to the input field instead of `document`, it should fix the both issues.

**Comment by gencer** [comment] 2019-09-02 15:31
> > I do not filter things. The `search` feature in Dropdown filters items by search `value`.
> 
> You can do this by `noop` `search` function: [codesandbox.io/s/semantic-ui-example-6213c](https://codesandbox.io/s/semantic-ui-example-6213c)
> This option is also more accessible.
> 

Well, this is much much cleaner. I will use this way. (Instead of monkey-patching)

Thank you!

> And now I see that your issue is closer to #3146. As now we improved focus handling, probably we can try to bind event listeners to the input field instead of `document`, it should fix the both issues.

Will be great in both way.
