### ISSUE TITLE
onSearchChange randomly misses keys on IE11 if typing quickly

### ISSUE THREAD

**Issue by abaltodanorb** [Semantic-Org/Semantic-UI-React#1785] opened 2017-06-21 15:53 UTC
I have a simple search dropdown with autocomplete. 
<Dropdown
                search={true}
                onSearchChange={onSearch}
                onBlur={null}
                onFocus={onFocus}
                onChange={onClick}
                noResultsMessage={noResultsMessage}
                minCharacters={0}
                options={options}
                text={title}
                open={open}
                floating selection scrolling
</Dropdown>

When I type text very quickly, every now and then, the corresponding onSearchChange event goes missing. For example, if I type "foobar", the input field may end up showing "foobr".

This happens only on IE (tested with IE11 on Windows 7), and I have not seen this on any other browser.

### Version
0.68.5

**Comment by layershifter** [comment] 2017-06-23 07:19
I will try to check it on this weekend.

**Comment by layershifter** [comment] 2017-06-24 14:18
I've made a [codepen](https://codepen.io/layershifter/pen/XgaLKP) and tested it Win8/IE11, I can't reproduce the described problem. Can you check my codepen and possible update it, so that we will can reproduce the problem? I should note that the problem is rather strange.

**Comment by layershifter** [comment] 2017-06-28 16:59
Bump @abaltodanorb

**Comment by layershifter** [comment] 2017-07-03 12:58
There is no feedback, so I closed this issue.

**Closed as completed** 2017-07-03 12:57 UTC
Labels: needs author feedback
