### ISSUE TITLE
Dropdown menu works only for the first click

### ISSUE THREAD

**Issue by ramigg** [Semantic-Org/Semantic-UI-React#1108] opened 2017-01-02 10:01 UTC
After clicking dropdown menu once it doesn't respond anymore.
It happens here: http://react.semantic-ui.com/collections/menu

**Comment by svrcekmichal** [comment] 2017-01-02 11:54
Hi, your issue is duplicate of #659 For me solution of @eXtreme worked.

**Comment by layershifter** [comment] 2017-01-02 21:37
Yep, it's duplicate of #659.

**Closed as completed by layershifter** 2017-01-02 21:37 UTC
Labels: duplicate

**Comment by levithomason** [comment] 2017-01-24 21:03
Released in `semantic-ui-react@0.64.4`.
