### ISSUE TITLE
After Install Semantic ui react my react app is not working showing totally white page

### ISSUE THREAD

**Issue by raihan-biswas-dev** [Semantic-Org/Semantic-UI-React#4329] opened 2022-01-26 22:02 UTC
After Install Semantic ui react my react app is not working showing totally white page

**Comment by kaocher2021** [comment] 2022-01-26 22:04
I m facing same problem... raihan-biswas-dev...    I need an proper solution

**Comment by blue-hexagon** [comment] 2022-01-28 18:07
I just installed Semantic UI on a fresh React install - I didn't reproduce the issue.
      
    "dependencies": {
        "@testing-library/jest-dom": "^5.16.1",
        "@testing-library/react": "^12.1.2",
        "@testing-library/user-event": "^13.5.0",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-scripts": "5.0.0",
        "semantic-ui-css": "^2.4.1",
        "semantic-ui-react": "^2.1.1",
        "web-vitals": "^2.1.4"
      },

**Comment by brianespinosa** [comment] 2022-01-28 20:33
@raihan-biswas-dev please complete the full bug report form. We have no idea what your app toolchain looks like, what version of semantic ui react you are using, etc. Your report contains no information as to what sorts of error you are getting in your console, etc.

I am closing this report due to no actionable info, but we can reopen if a reproduction case and a full report is provided.

**Closed as completed by brianespinosa** 2022-01-28 20:33 UTC
Labels: needs author feedback
