### ISSUE TITLE
fix(Dropdown): your description

### ISSUE THREAD

**Issue by assumer** [Semantic-Org/Semantic-UI-React#1801] opened 2017-06-26 17:20 UTC
**Steps to Reproduce**
1. Click on the Drop down menu
2. Click on the search field.

**Expected**
The Dropdown should keep open and search would work

**Result**
The Dropdown just closes and cant do filter

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-in-menu
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment] 2017-06-28 16:58
@assumer Thanks for report, however it's duplicate of #1593. PRs are welcome.

**Closed as completed by layershifter** 2017-06-28 16:58 UTC
Labels: duplicate
