### ISSUE TITLE
Modal is not centered

### ISSUE THREAD

**Issue by empz** [Semantic-Org/Semantic-UI-React#2704] opened 2018-04-05 20:00 UTC
### Steps
1. Use a `<Modal>` component.

### Expected Result
Modal should be centered

### Actual Result
Modal is not centered, but in top-left corner.

### Version
0.79.0

### Testcase
[Codesandbox showing the bug](https://codesandbox.io/s/881lk0rx09)

Also, it's not a CSS issue because the same code using plain SUI works well as shown in [this CodePen](https://codepen.io/emzero/pen/XExNEB?editors=1010):

**Comment by brianespinosa** [comment] 2018-04-05 20:05
Duplicate of #2550

**Closed as completed by brianespinosa** 2018-04-05 20:05 UTC
Labels: triage
