### ISSUE TITLE
Portal/TransitionablePortal closes on Popup close

### ISSUE THREAD

**Issue by nolawnchairs** [Semantic-Org/Semantic-UI-React#3740] opened 2019-08-07 03:23 UTC
This has been addressed before, but the issue is two years old, so I'm re-addressing it, as it points out a violation in the "controlled" aspect of components.

As I understand, the `open` prop in the `TransitionablePortal` component should control the visibility/open-state of the portal and should not be affected by any other state-derived influence.

Basically, I would like to use `Popup` components containing more complex data (other than strings) inside an animated modal or any component housed in a portal.

This issue is not present if the `Modal` is not inside `TransitionablePortal` or standard `Portal`, and works correctly, but at the expense of not utilizing the smoother, animated transition. This issue *is* present in a standard, non-animated `Portal` as well. This makes sense, since `TransitionablePortal` is just sugar for `Portal` and `Transition`.

A contrived example is provided at CodeSandbox that illustrates the issue:
https://codesandbox.io/s/react-typescript-c4mdl

### Steps
Create a controlled `Popup` inside a `Modal` that's itself inside TransitionablePortal` or `Portal`
Close that popup via state

### Expected Result
The `Popup`should close

### Actual Result
The `Popup` closes but the `TransitionablePortal`it's contained in closes also

### Version
Latest version as loaded into the CodeSandbox example provided

### Testcase
https://codesandbox.io/s/react-typescript-c4mdl

**Comment by r3vsan** [comment] 2019-08-28 12:34
Same issue using a calendar popup component inside a TransitionablePortal: selecting a day or navigating between months in the calendar closes the Portal.

**UPDATE**

In my case adding:
`closeOnDocumentClick={false}`
resolve the issue.

**Comment by jeanfortheweb** [comment] 2019-09-23 09:59
Confirmed, happens only on TransitionablePortal, a normal Portal works fine.

**Comment by brianespinosa** [comment] 2020-07-29 17:30
Closing this issue as it looks like this is no longer an issue when using the latest v1.0.0 release.

https://codesandbox.io/s/react-typescript-th25r

**Closed as completed by brianespinosa** 2020-07-29 17:30 UTC
Labels: bug
