### ISSUE TITLE
Attached <Button /> does not respond on keyboard events

### ISSUE THREAD

**Issue by odragora** [Semantic-Org/Semantic-UI-React#1797] opened 2017-06-24 21:30 UTC
### Steps
Create a Button with an `attached` property.

### Expected Result
The button is accessible for keyboard users (hit Space or Enter and the button pressed).

### Actual Result
The button does not receive keyboard input.

### Version
0.70.0

### Testcase
https://codepen.io/anon/pen/jwGEYJ

**Comment by layershifter** [comment] 2017-06-29 14:53
@odragora The problem is that when the `Button` is `attached` or contains a `label`, it's rendered as `div` while in all other cases as `button`. And it's correct in these cases.

You can use `tabIndex` and `role` props to gain focus, however will also be [necessary](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role) to add a key event handler that listens for the Space key in order to be consistent with native buttons.

I'm not sure that it's should be fixed by library, but I think that we need to add an example to our docs. @levithomason what you think?

**Comment by levithomason** [comment] 2017-07-10 20:38
Hm, it seems the responsible thing to do here is to render the div with the appropriate props to behave as a button.

**Closed as completed** 2017-08-13 16:54 UTC
Labels: needs engineering
