### ISSUE TITLE
Enter key handler for Search?

### ISSUE THREAD

**Issue by dw-ll** [Semantic-Org/Semantic-UI-React#3903] opened 2020-02-27 07:17 UTC
Is there a feature/prop that handles or triggers handleResultSelect with the current input value for the Search module when the enter/return key is pressed? I dove into the code and found selectItemOnEnter and could not figure out how to utilize it.

**Comment by brianespinosa** [comment] 2020-07-29 16:58
I believe this is a duplicate of #3994 which should be resolved by a recently merged PR.

**Closed as completed by brianespinosa** 2020-07-29 16:58 UTC
Labels: duplicate

**Comment by SiOuz** [comment] 2021-03-06 07:53
Its not on official documentation, but you can do that (you inherit it from base component) :
Works fine for me, with typescript.
```
  onKeyPress={(event: React.KeyboardEvent) => {
    console.log(event.key);
  }}
```
