### ISSUE TITLE
[View][Advertiesement] - online demo page is broken

### ISSUE THREAD

**Issue by DimalChandrasiri** [Semantic-Org/Semantic-UI-React#3337] opened 2018-12-13 18:46 UTC
## Bug Report
The online documentation and demo page for **Views** -> **Advertisement** shows a 404.

### Steps
Navigate to **Advertisement** online demo page. 

### Expected Result
The actual demo page of views, advertisement page.

### Actual Result
![image](https://user-images.githubusercontent.com/11191791/49959999-19713800-ff35-11e8-9312-6c4ae5011fb4.png)

### Version
0.84.0

**Comment by layershifter** [comment] 2018-12-13 19:57
Duplicate of #3164, you need to disable your Adblock. I've submitted a report to them, hope that it will help. The previous fix was enough, but now they have a filter for `/advertisement/*` 💣 

It also possible to open it via direct link: https://react.semantic-ui.com/views/advertisement/

**Closed as completed by layershifter** 2018-12-13 19:57 UTC
Labels: duplicate
