### ISSUE TITLE
Classes not getting applied

### ISSUE THREAD

**Issue by oullah** [Semantic-Org/Semantic-UI-React#1479] opened 2017-03-19 18:28 UTC
I'm not really sure if this is a Semantic issue or a React issue...so I am going to try here first. I'm running Semantic UI React in Electron. The issue I am seeing is the full style isn't getting applied from classes. For example I am trying to load a Flag element: 
```        
        <div>
          Flag<br />
          <Flag name="us" />
        </div>
```

However, the CSS definitions for `i.flag.us` aren't getting loaded:

![screenshot 50](https://cloud.githubusercontent.com/assets/8106661/24083583/32141d60-0cb0-11e7-8b84-3978c28b918e.png)

You can see that the sementic.css file is loaded, and the body styles have been applied, but not the `i.flag.us` styles. You can also see in the screenshot that this is happening for all the other styles as well (e.g. button). Any ideas?

**Comment by oullah** [comment] 2017-03-19 19:30
I found a workaround. Instead of doing `import 'semantic-ui-css/semantic.css'`, I copied semantic directly into my app and used a `<link rel="stylesheet" href="./semantic/semantic.css">` tag instead. Would like to use the node module instead, any suggestions?

**Comment by levithomason** [comment] 2017-03-19 23:34
Hm, the generated HTML looks correct.  Not sure what the problem is here.

About a year ago, I built a desktop app with Electron and Semantic UI React (called Stardust at the time).  I was able to import the css with ES imports, [see here](https://github.com/3-strand-code/3sc-desktop/blob/master/app/index.js#L2).  You can see the webpack loader [here](https://github.com/3-strand-code/3sc-desktop/blob/master/webpack.base.babel.js#L21).

I'll close this for now since there doesn't appear to be any bugs with SUIR, but feel free to keep the convo going if necessary.

**Closed as completed by levithomason** 2017-03-19 23:34 UTC
Labels: question

**Comment by rnikoopour** [comment] 2021-01-05 23:22
Super sorry to Necro this nearly 4 year old thread but I've run into the same thing today.

If I put `import 'semantic-ui-css/semantic.min.css'` into my `index.tsx` it isn't respected by electron


But if I import the CSS in my `index.html` using:
```
<link
  async
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.1/dist/semantic.min.css"
/>
<script
  async
  src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.1/dist/semantic.min.js"
></script>
```

Electron will respect semantics css.

**Comment by brianespinosa** [comment] 2021-01-06 23:07
@rnikoopour that has nothing to do with Semantic UI React. The package you are importing from is from an entirely different package. This has something to do with the build toolchain you are using in your application.

**Comment by SonataOto** [comment] 2021-05-02 06:54
> Super sorry to Necro this nearly 4 year old thread but I've run into the same thing today.
> 
> If I put `import 'semantic-ui-css/semantic.min.css'` into my `index.tsx` it isn't respected by electron
> 
> But if I import the CSS in my `index.html` using:
> 
> ```
> <link
>   async
>   rel="stylesheet"
>   href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.1/dist/semantic.min.css"
> />
> <script
>   async
>   src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.1/dist/semantic.min.js"
> ></script>
> ```
> 
> Electron will respect semantics css.

Hi! Sorry about re-open this issues.

( _If this is with "Webpack" dependency!_ )
You need import your css from node_modules to another css file in your app.
[https://github.com/webpack-contrib/sass-loader#imports](https://github.com/webpack-contrib/sass-loader#imports)

Something like this:

File: `project_root/src/App.global.css`

Code: `@import '~css-dependency/bootstrap.css';`

Prepend a "~" to css file paths that are in your node_modules!
