### ISSUE TITLE
Popper.js -> popup doesn't scroll when the overflow parent is not body

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI-React#3617] opened 2019-05-23 12:24 UTC
## Bug Report
The Popup doesn't scroll when the overflow parent is not body.

### Steps
See https://codesandbox.io/s/semantic-ui-react-y0yce -> hover over red square and scroll down.

### Expected Result
Popup scrolls up with square (as shown here):

![](https://user-images.githubusercontent.com/14183168/54908052-abeb8500-4eef-11e9-81d4-4b2d32849ef3.gif)

### Actual Result
Popup stays in the place it was triggered, while content moves up.

### Version
0.87.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-y0yce

**Comment by rijk** [comment] 2019-05-23 13:27
I think this is a duplicate of #3569 and will be fixed with #3607.

**Comment by layershifter** [comment] 2019-05-26 15:48
Yep, it's duplicate of #3569.

**Closed as completed by layershifter** 2019-05-26 15:48 UTC
Labels: duplicate
