### ISSUE TITLE
Modal Blinking in Chrome

### ISSUE THREAD

**Issue by david-chh** [Semantic-Org/Semantic-UI-React#1494] opened 2017-03-22 00:27 UTC
I want Scrolling Modal but i tried with basic modal. It is blinking in chrome but working perfect in firefox.

https://react.semantic-ui.com/modules/modal#modal-example-scrolling

**Comment by layershifter** [comment] 2017-03-22 14:37
I've tested it in Chrome `56.0.2924.87` and `57.0.2987.110` under Windows. I don't see blinking there.

Can you post your version? Is it latest?

**Comment by david-chh** [comment] 2017-03-22 15:42
Thanks for your reply. I have checked in chrome and firefox also now. Its blinking.

chrome Version 57.0.2987.110 (64-bit)

Note: I am using Other components also from react-semantic-ui so there is no integration problem.

**Comment by layershifter** [comment] 2017-03-23 08:13
I can't reproduce this on any from my devices.

I'm think it's problem with your PC and video drivers, possible with [hardware acceleration](http://askubuntu.com/questions/766725/annoying-flickering-in-16-04-lts-chrome) because I had same problems some time ago.

**Comment by philjoseph** [comment] 2017-03-23 14:57
This is happening to our developers using ubuntu and to one using Windows 10 but not to those using MacOS.

See this short screencast showing the effect:  https://slack-files.com/T0VNSF68H-F4NL9M950-ae64b77fc1. 

Note the this issue happen on Chrome 56.0.2924.87 (64-bit) and Ubuntu 16.04 LTS and also a chrome beta we just installed on the ubuntu maching (58). Any way we can help you analyzing this issue ?

**Comment by layershifter** [comment] 2017-03-23 15:12
Do you have same issues with SUI [Modal](https://semantic-ui.com/modules/modal.html#scrolling-modal)?

**Comment by philjoseph** [comment] 2017-03-23 15:21
We are using http://react.semantic-ui.com/modules/modal and this blinking happen on all types of modal, standard, basic, scrolling

**Comment by layershifter** [comment] 2017-03-23 15:26
I understand, but do have same issues with [SUI modals](https://semantic-ui.com/modules/modal.html#/definition)?

**Comment by levithomason** [comment] 2017-03-25 17:49
@philjoseph Does this happen using the doc site example in the OP?

http://react.semantic-ui.com/modules/modal#modal-example-scrolling

**EDIT**
Fix protocol in doc link.

**Comment by philjoseph** [comment] 2017-03-26 07:12
@levithomason Indeed this happen with the 3 modal samples (basic, standard and scrolling). It also also happen with the confirm sample.
Additional information that may be worth notifying: 
 * The dialog are taking the whole height of the page even for confirm
 * We are working in right-to-left

**Comment by philjoseph** [comment] 2017-03-26 11:39
We finally found the root cause of our issue: we are also using in our project bootstrap table to obtain the additional functionalities it offers (Insert, Delete, Export...) and it uses a css class named Modal that conflicts with the semantic Modal. 
I do not know if this is the case of @david-chh but for us, we just add some CSS code to change the some property. If you could namespace your CSS you could avoir having issues like this one.

**Comment by levithomason** [comment] 2017-03-26 17:51
Ah, I should have been more explicit. I meant to say does this happen on the doc site itself.  We've seen this before in https://github.com/Semantic-Org/Semantic-UI-React/issues/794. 

As warned there, this is not supported and I'd highly recommend not using both Bootstrap and SUI together. More details in the linked issue. 

Closing this for now. Will reopen if @david-chh is having issues with the supported usage and we can get a repro case. Currently all tests are passing and docs are working for supported usages.

**Closed as completed by levithomason** 2017-03-26 17:51 UTC
Labels: invalid

**Comment by sag1v** [comment] 2018-03-22 10:45
@levithomason can you please respond to my [comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/794#issuecomment-371435813)? I'm curious to know what you think.

**Comment by sag1v** [comment] 2018-03-22 10:45
@levithomason can you please respond to my [comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/794#issuecomment-371435813)? I'm curious to know what you think.

**Comment by layershifter** [comment] 2018-03-22 12:03
Don't spam, please.
