### ISSUE TITLE
Modal: inside modal is closing when clicking on contents

### ISSUE THREAD

**Issue by xumix** [Semantic-Org/Semantic-UI-React#2988] opened 2018-07-08 11:21 UTC
### Steps
Upgraded from semantic-ui-react@0.81.1 to 0.82

### Expected Result
Clicking inside modal does nothing

### Actual Result
Modal is closed when clicking on any modal contents, 0.81.1 worked OK

### Version
 0.82

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by levithomason** [comment] 2018-07-08 20:43
I cannot reproduce this on our docs which are running 0.82.0.  Tests are also passing.  Closing for now.  We will reopen if we can get a repro case.

https://react.semantic-ui.com/modules/modal#types-modal

**Comment by xumix** [comment] 2018-07-09 08:37
I've found the repro, the issue is found if modal is opened inside other modal. It can be reproduced in docs
https://react.semantic-ui.com/modules/modal#types-multiple

**Closed as completed** 2018-07-09 13:25 UTC
Labels: bug

**Comment by xumix** [comment] 2018-07-09 13:29
@layershifter thanks!
