### ISSUE TITLE
Dropdown: search string with space causes select the first option

### ISSUE THREAD

**Issue by honzajerabek** [Semantic-Org/Semantic-UI-React#3764] opened 2019-08-28 12:03 UTC
### Steps
1. Have a Dropdown (both `selection` and `search` true) and options that are multiple words starting same first word
2. Open the dropdown and start typing the first word, that is common for some number of options
3. Press space to continue writing
4. the first available option is immediately selected

note: I've tried number of combinations of `selectOnNavigation`, `selectOnBlur` props as well as stopping propagation on `onSearchChange` and other events

### Expected Result
Dropdown lets me to search any string I want

### Actual Result
Dropdown cuts typing the search word on the spacebar press and selects the first available option from the search results

### Version
0.88.0

### Testcase
https://codesandbox.io/s/semantic-ui-react-9undx

**Comment by ambroselittle** [comment] 2019-08-28 21:41
This issue undoubtedly is caused by this: https://github.com/Semantic-Org/Semantic-UI-React/pull/3702 

That PR should be named "force" selection not "allow". :D  

Suggestion that if search is enabled, this behavior is not enabled. And/or add an option to configure. But really, it shouldn't happen during search.

**Comment by evanstern** [comment] 2019-08-28 21:49
Yes, at the very least this needs to be an option, not the default.

**Comment by ambroselittle** [comment] 2019-08-28 22:09
By the way, temporary workaround that tested OK for us - downgrade to 0.87.3. Unless you need something in 0.88, of course.

**Comment by honzajerabek** [comment] 2019-08-29 06:12
> Suggestion that if search is enabled, this behavior is not enabled. And/or add an option to configure. But really, it shouldn't happen during search.

@ambroselittle Agree, it does behave like that in non-react semantic-ui - https://jsfiddle.net/Lqanh61p/1/

i guess I'll have some time to make a pr

**Comment by evanstern** [comment] 2019-08-29 12:11
> i guess I'll have some time to make a pr

👍 -- ~I was about to say the same thing but if you want to do this that's fine with me!~ (just saw that you already submitted it)

> By the way, temporary workaround that tested OK for us - downgrade to 0.87.3. Unless you need something in 0.88, of course.

Yeah, we want the fixes in 0.88 that stop message spam about `UNSAFE_` lifecycle methods so I'd rather not downgrade. Luckily, we are at a place in development where we can live with a buggy UI element until it gets fixed.

**Comment by layershifter** [comment] 2019-09-02 13:13
Thanks for reporting and special thanks to @honzajerabek 🍾 
Will be released during this week 👍

**Comment by layershifter** [comment] 2019-09-09 17:10
Release in `0.88.1` 🚀

**Closed as completed by layershifter** 2019-09-09 17:10 UTC
Labels: bug
