### ISSUE TITLE
Can show flags instead of text in Select addon

### ISSUE THREAD

**Issue by mehrad77** [Semantic-Org/Semantic-UI-React#3468] opened 2019-02-27 13:31 UTC
### Problem description
currently, select tags are showing like this: 
![screenshot from 2019-02-27 16-56-03](https://user-images.githubusercontent.com/8453360/53493475-a34e8d00-3ab0-11e9-8fd8-1a7a14e89f6e.png)
which it's data comes from an object like this:
```
{
  { key: 'af', value: 'af', flag: 'af', text: '+93' },
  { key: 'cn', value: 'cn', flag: 'cn', text: '+14' }
}
```
But how can show flags inside of choose Select option instead of text? (`+93` in this example)

### Proposed solution
Well, I don't know how `<Select />` is designed but since we have `<Flag />` component, it shouldn't be hard to implement this.

**Comment by layershifter** [comment] 2019-02-27 13:47
Duplicate of #1147, see the issue and Codesandbox for workarouds: https://codesandbox.io/s/qo4mrr5n9

**Closed as completed by layershifter** 2019-02-27 13:47 UTC
Labels: duplicate
