### ISSUE TITLE
'semantic-ui-css is overriding my custom component styling

### ISSUE THREAD

**Issue by Afreeca** [Semantic-Org/Semantic-UI-React#3977] opened 2020-07-06 22:06 UTC
## Bug Report

I imported the import 'semantic-ui-css/semantic.min.css into my index.js
and all the semantic components were working fine, but at same time it's overriding some of my custom components styling, and it's shouldn't, it seems to be applying a generic styling to HTML tags. And I tried everything, probably I will end up choosing a different library, but I don't believe this is the desired  behavior

**Comment by webdestroya** [comment] 2020-07-08 02:46
Are your components less specific? CSS will always select the _MOST_ specific rule that matches.

**Comment by Afreeca** [comment] 2020-07-08 11:44
No, pure CSS, I discovered that it is applying global styling to my Headings(h1, h2, etc...). what are my alternatives? There is any way I can prevent this to happen without using Less

**Comment by webdestroya** [comment] 2020-07-09 02:47
what do you mean by "applying global styling"? I think your problem is whatever rule you have is just being superseded by the semantic-ui ones because your rule is not specific enough.

can you paste one of your styles?

**Comment by Afreeca** [comment] 2020-07-09 10:49
I'm using styled-components as you can see and they are only be imported at component level:

example, this H1 margin was being overridden
```
export const **example** = styled.h1`
    margin:10px;
    font-family: serif;
    font-weight: 600;
    color: ${({theme}) => theme.textColor};
    font-size: 20px;
    line-height: 39px;
    letter-spacing: 0;
    padding-bottom: 5px;
    @media ${devices.tablet} {
      font-size: 16px;
    }
    @media ${devices.mobile} {
      font-size: 12px;
    }
`;
```
this is sematic css that is overriding

```
h1:last-child, h2:last-child, h3:last-child, h4:last-child, h5:last-child{
margin-bottom: 0;
}
```

**Comment by webdestroya** [comment] 2020-07-09 22:48
![image](https://user-images.githubusercontent.com/269746/87098091-64c7f700-c1fb-11ea-8f26-1dedcbd7e143.png)

It looks like the `h1:first-child` is being overridden by the class I added (`something-i-just-added`) but then is being overridden by semantic's `.ui.header:first-child` because that is more specific. You need to put more conditions on the rule.

Sorry if I am not understanding your issue correctly. Maybe you could post the inheritance tree like above to show the problem?

**Comment by brianespinosa** [comment] 2020-07-10 19:16
@Afreeca @webdestroya I am going to go ahead and close this. The issue is due to CSS specificity. Additionally, none of the CSS is included in this repository at all.

@webdestroya suggestion of making the CSS more specific is what is needed to make the expected styles work. That is not unique to SUIR or SUI, that is just how CSS specificity works.

@Afreeca if you would like to make a working Codepen that shows the problem you are having with the link we provide in our bug report template, I would be happy to show you how to make your CSS more specific.

**Closed as completed by brianespinosa** 2020-07-10 19:16 UTC
Labels: question
