### ISSUE TITLE
Sidebar don`t open after modal close

### ISSUE THREAD

**Issue by nikolasmach23** [Semantic-Org/Semantic-UI-React#4143] opened 2021-01-18 10:19 UTC
### Steps
Hi, i would like to ask you if there is any solution. When i closed modal i can`t open sidebar from Menu. I took codesandbox with the same issue created at 15.November

### Expected Result
Open sidebar.

### Version
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-scripts": "4.0.1",
"semantic-ui-css": "^2.4.1",
"semantic-ui-react": "^2.0.2"

### Testcase
https://codesandbox.io/s/crazy-tree-r5m0o

**Comment by layershifter** [comment] 2021-01-18 11:15
Duplicate of #4110.

**Closed as completed by layershifter** 2021-01-18 11:15 UTC
Labels: duplicate
