### ISSUE TITLE
Grid with custom number of columns + columns with custom width

### ISSUE THREAD

**Issue by meglio** [Semantic-Org/Semantic-UI-React#4225] opened 2021-07-10 10:30 UTC
```jsx
<Grid columns={12}>
  <Grid.Column width={4}>  Col 1  </Grid.Column>
  <Grid.Column width={4}>  Col 2  </Grid.Column>
  <Grid.Column width={4}>  Col 3  </Grid.Column>
</Grid>
```

This does not work. Rendered are columns of such a width as if they were in a 16-columns table.

Am I doing it wrong?

**Comment by layershifter** [comment] 2021-07-11 14:16
Duplicate of #4127.

**Closed as completed by layershifter** 2021-07-11 14:16 UTC
Labels: duplicate
