### ISSUE TITLE
Refs are not passed to components

### ISSUE THREAD

**Issue by neutraali** [Semantic-Org/Semantic-UI-React#3915] opened 2020-03-23 15:51 UTC
This is super confusing and feels like the `ref` -prop isn't being consistently supported through SUIR.

For example:

1. **Input** (others?) supports `ref` [Link](https://react.semantic-ui.com/elements/input/#usage-ref-focus)
2. **Image**  (others?) does _not_ support `ref` [Link](https://react.semantic-ui.com/elements/image/)
3. **Ref** is being referenced in past issues [Link](https://github.com/Semantic-Org/Semantic-UI-React/issues/3717)
4. **Ref** is removed from docs; moved to _Stardust UI_ || _Fluent UI_ || _Whatever UI_ [Link](https://github.com/Semantic-Org/Semantic-UI-React/pull/3774)

Let's say I want to:
```javascript
import Image from 'semantic-ui-react';

let ref = React.useRef(null);
let image = () => <Image ref={ref} />
```

What is the current style of passing `ref`? Would be awesome if this was stated somewhere in the SUIR docs in large, bolded letters.

**Comment by traverse** [comment] 2020-06-24 11:50
Actually ran into the same problem when trying to implement drag and drop on a table, table rows don't pass refs either.

**Comment by layershifter** [comment] 2020-06-26 08:04
@neutraali you're totally right. This is extremely confusing 🤕 

Convergence effort is dead so I will not even try to move it forward, I will revert #3774 to move back docs for `Ref`s 🔙 

Current big goal is to get rid of deprecated lifecycle methods (#3919), the next big goal will be solve `ref`s issues and use `React.forwardRef`.

**Comment by brianespinosa** [comment] 2020-07-28 18:00
@layershifter I think this would also have to be a breaking major version change now that we officially published at 1.0.0 version. @levithomason should we update the docs to mention that since we have a full major version release that we want to stick to semantic versioning while in maintenance?

Also @layershifter I have seen you taking some time to go in and clean up some of the open issues here while also working refactoring for all of the `UNSAFE_*` methods. Thank you! I am going to make an effort to go through and respond to at least a few open issues every day that are still in the `triage` bucket.

**Comment by brianespinosa** [comment] 2020-07-29 17:11
Duplicate of #3819

**Closed as completed by brianespinosa** 2020-07-29 17:11 UTC
Labels: duplicate

**Comment by layershifter** [comment] 2020-08-17 09:44
FYI: this #4039 PR restores docs for `Ref` component.
