### ISSUE TITLE
Dropdown (allowAdditions): newly added items do not display correctly

### ISSUE THREAD

**Issue by scottohara** [Semantic-Org/Semantic-UI-React#2624] opened 2018-03-09 02:18 UTC
Apologies if this is a duplicate.  I _suspect_ the issue described below may be caused by an incorrect `selectedIndex` value, and I'm aware that there are already multiple similar issues that are currently being addressed via https://github.com/Semantic-Org/Semantic-UI-React/pull/2375; though I'm unsure if the issue below falls into the same category as those previous ones.

(Also note: I'm new to Semantic-UI-React; so it is entirely possible that this isn't a bug at all, and simply something wrong with the test case example).

### Steps
(using the test case link below)

##### a) Select an existing item from the list:
1. Click the dropdown (to show the options list)
2. Select `Arizona` by clicking on it
3. Click the dropdown again (to show the options list again)

##### Note that:
1. The input area displays a blinking cursor and the text `Arizona` in grey (styled as placeholder text)
2. The corresponding `Arizona` item in the options list is highlighted with **both** a grey background **and** bold text

##### b) Add a new item to the list:

1. Click the dropdown (to show the options list)
2. Enter the text `abcd` and click the "**Add** abcd" option that appears
3. Click the dropdown again (to show the options list again)

##### Note that:
1. The input area shows a blinking cursor and the text `Alabama` in grey
2. The `Alabama` item in the options list is highlighted with a grey background
3. The `abcd` item in the options list is shown with bold text

### Expected Result

Regardless of whether an existing item is selected or a new item is added, when the dropdown is opened a second time the behaviour should be the same:

✅ The input area displays the text of the _currently selected_ option (in grey)
✅ The list highlights the _currently selected_ option with a grey background
✅ The list highlights the _currently selected_ option in bold

### Actual Result

After entering a new item, when the dropdown is opened a second time:

❌ The input area reverts to display the text of the _first_ option (in grey)
❌ The list highlights the _first_ option with a grey background
✅ The list highlights the _currently selected_ option in bold

### Version
0.78.3

### Testcase
https://codepen.io/anon/pen/aYbEXo?editors=0010

**Comment by levithomason** [comment] 2018-04-13 15:45
Yep, bug. Great report ❤️, makes my day to see issues posted like this!

I've forked the test case to show print state to the DOM.  The data (options) and the value of the dropdown are both correct during this flow, however, the logic for setting the selected (highlighted) item is incorrect.  See https://codepen.io/anon/pen/EEzGyQ?editors=0010.

I believe this is a dupe of https://github.com/Semantic-Org/Semantic-UI-React/pull/2375 as you've pointed out.  I will close this in favor of that issue.  If we find differences, or the same issue in that PR let's address it there as well, please.  Thanks again.

**Closed as completed by levithomason** 2018-04-13 15:45 UTC
Labels: duplicate
