### ISSUE TITLE
Dropdown gives me a "findDOMNode is deprecated in StrictMode" warning

### ISSUE THREAD

**Issue by sparrowV** [Semantic-Org/Semantic-UI-React#4103] opened 2020-11-07 08:54 UTC
## Bug Report
I have the following code in one of my components.
`      <Dropdown item text={userName}>
           </Dropdown>`

just empty dropdown with no options. It gives me the following warning:

```
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefFindNode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Dropdown)
    in RefFindNode (created by Ref)
    in Ref (created by Dropdown)
    in Dropdown (at UserAvatar.js:18)
    in span (at UserAvatar.js:17)
    in UserAvatar (at Header.js:11)
    in div (created by Header)
    in Header (at Header.js:10)
    in div (created by Segment)
    in Segment (at Header.js:9)
    in Header (at Home.js:22)
    in div (at Home.js:21)
    in Home (created by Context.Consumer)
    in Route (at App.js:19)
    in div (at App.js:17)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:16)
    in PersistGate (at App.js:15)
    in Provider (at App.js:14)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```

How can it be fixed?
### Steps
Just use Dropdown in on the the components

### Expected Result
no warnings

### Actual Result
warning that I mentioned above

### Version
latest

**Comment by layershifter** [comment] 2020-11-07 09:43
Duplicate of #3819.

**Closed as completed by layershifter** 2020-11-07 09:43 UTC
Labels: duplicate
