### ISSUE TITLE
Header + Icon; unwanted new line for a particular icon ("content")

### ISSUE THREAD

**Issue by cristian-spiescu** [Semantic-Org/Semantic-UI-React#3925] opened 2020-03-31 16:23 UTC
### Steps

A simple usage of Header + Icon, taken from the examples. But modified the icon name to `content`.

```jsx
    <Header as="h2">
      <Icon name="content" />
      <Header.Content>
        Account Settings
        <Header.Subheader>Manage your preferences</Header.Subheader>
      </Header.Content>
    </Header>
```

### Expected Result

Correct alignment like in:

![image](https://user-images.githubusercontent.com/4469897/78050453-843dc100-737c-11ea-8c3a-da84e92a27e7.png)

### Actual Result

A new line is inserted, so the icon is no more aligned.

![image](https://user-images.githubusercontent.com/4469897/78050482-928bdd00-737c-11ea-8f41-be0da52f342a.png)

### Version
0.88.2

### Testcase

https://codesandbox.io/s/semantic-ui-react-r1469

**Comment by solmalisani** [comment] 2020-05-12 15:07
Hello I would like to work in this!

**Comment by brianespinosa** [comment] 2020-07-28 19:51
@cristian-spiescu this is an issue with the CSS and I can confirm it is also present in the parent Semantic UI project where all of our styles come from. Since this is a CSS issue from the upstream parent project, I am closing this report as we have no control over those styles.

@solmalisani if you want to work on a solution to that issue with the CSS, you could submit a PR to the parent project. 🙌

**Closed as completed by brianespinosa** 2020-07-28 19:51 UTC
Labels: CSS bug

**Comment by layershifter** [comment] 2020-07-29 14:11
I opened an issue in Fomantic UI: https://github.com/fomantic/Fomantic-UI/issues/1620

**Comment by lubber-de** [comment] 2020-08-08 10:15
Just use an alias icon name `bars` or `sidebar`

```jsx
<Header as="h2">
  <Icon name="bars" />
  <Header.Content>
    Account Settings
    <Header.Subheader>Manage your preferences</Header.Subheader>
  </Header.Content>
</Header>
```

**Comment by cristian-spiescu** [comment] 2020-08-09 15:07
Thanks! So it seems to be particular only to the icon named `content`, which is kind of special and used in a lot of places in the CSS.
