### ISSUE TITLE
fix(Modal): Message dismiss on modal closes modal

### ISSUE THREAD

**Issue by mosheavni** [Semantic-Org/Semantic-UI-React#2429] opened 2018-01-13 22:29 UTC
**Steps to Reproduce**
```
1. Create a controlled modal with `handleOpen` and `handleClose` exactly like the example
2. Inside the modal, create a Message component that's handled by a dedicated state, and has `onDismiss` that changes the state
3. Try to dismiss the message and see that the modal closes
```

**Expected**
The Modal should not close when dismissing a `Message` component

**Result**
Described above.

**Testcase**
https://codepen.io/moshem/pen/ZvRNOg

**Comment by sharno** [comment] 2018-01-16 15:39
Possibly same issue of #1580 
I have the same issue too. With any change of the components rendered inside the modal, the onClose is triggered

**Comment by layershifter** [comment] 2018-01-16 18:46
Yes, it's duplicate of #1580 and can be solved with published there workaround.

**Closed as completed by layershifter** 2018-01-16 18:46 UTC
Labels: duplicate
