### ISSUE TITLE
using umd in script tag is broken

### ISSUE THREAD

**Issue by soederpop** [Semantic-Org/Semantic-UI-React#3565] opened 2019-04-11 20:24 UTC
### Steps

Try including the semantic-ui-react umd build via script tag, and it is unavailable on window

### Expected Result

Expected to be able to use the library via a script tag and access via window.semanticUIReact

### Actual Result

```
typeof window.semanticUIReact === 'undefined'
```
### Version

0.86.0

### Testcase

You can see in the codesandbox that semanticUIReact is no longer put into window

https://codesandbox.io/s/jp7qrp41vy?fontsize=14

**Comment by soederpop** [comment] 2019-04-11 21:00
I was able to fix this in a fork by using

```
  entry: {
    [pkg.name]: `expose-loader?semanticUIReact!${paths.src('umd.js')}`,
  },
```

in your webpack umd config.  

tbh I thought webpack with libraryTarget `umd` and library `semanticUIReact` would have already done this for you (probably as it did previously).  

It might not since you don't have a default export?  I wish I could be more help

**Comment by layershifter** [comment] 2019-04-12 08:01
Duplicate of #3536 as was fixed in #3540, we also have a test that asserts for working UMD build:

![image](https://user-images.githubusercontent.com/14183168/56021527-577b3e80-5d12-11e9-9367-959ee61c644f.png)

**Closed as completed by layershifter** 2019-04-12 08:01 UTC
Labels: duplicate

**Comment by soederpop** [comment] 2019-04-12 15:08
Here's some simple HTML

```html
<html>
  <head>
      <script src="https://unpkg.com/react@16.8.4/umd/react.production.min.js"></script>
      <script src="https://unpkg.com/react-dom@16.8.4/umd/react-dom.production.min.js"></script>
      <script src="https://unpkg.com/semantic-ui-react@0.86.0/dist/umd/semantic-ui-react.min.js"></script>
      <script>
        alert(typeof window.semanticUIReact === 'undefined' ? 'Oh Crap' : 'Hmm')
      </script>
  </head>
  <body>
      <h1>hi</h1>
  </body>
</html>
```

here's the result:

![Screen Shot 2019-04-12 at 10 06 29 AM](https://user-images.githubusercontent.com/5178345/56047358-dc625a00-5d0a-11e9-913c-a13af8dbe9ba.png)

**Comment by soederpop** [comment] 2019-04-12 15:30
Here's that same HTML with the last working UMD build of semantic-ui, 0.84

```html
<html>
  <head>
      <script src="https://unpkg.com/react@16.8.4/umd/react.production.min.js"></script>
      <script src="https://unpkg.com/react-dom@16.8.4/umd/react-dom.production.min.js"></script>
      <script src="https://unpkg.com/semantic-ui-react@0.84.0/dist/umd/semantic-ui-react.min.js"></script>
      <script>
        alert(typeof window.semanticUIReact === 'undefined' ? 'Oh Crap' : 'Hmm')
      </script>
  </head>
  <body>
      <h1>hi</h1>
  </body>
</html>
```

Here's the result

![Screen Shot 2019-04-12 at 10 29 17 AM](https://user-images.githubusercontent.com/5178345/56048808-dfab1500-5d0d-11e9-868a-e0cb6232656b.png)

so this was working fine until 0.85

**Comment by layershifter** [comment] 2019-04-12 15:38
Fix was not released yet...
