### ISSUE TITLE
'Button' cannot be used as a JSX component.   Its instance type 'Button' is not a valid JSX element. 

### ISSUE THREAD

**Issue by selvak-d** [Semantic-Org/Semantic-UI-React#4368] opened 2022-05-12 10:34 UTC
## Bug Report
'Button' cannot be used as a JSX component.
  Its instance type 'Button' is not a valid JSX element. 
 <Button className="logout-button-ui" onClick={() => localStorage.setItem("data", JSON.stringify(data))}>

### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
{
  "name": "sampleApp",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "@azure/msal-browser": "^2.14.2",
    "@azure/msal-react": "^1.0.0",
    "@reduxjs/toolkit": "^1.8.0",
    "@types/blob-util": "2.0.0",
    "@types/jquery": "^3.5.14",
    "@types/react-datepicker": "^4.4.1",
    "@types/react-redux": "7.1.9",
    "admin-lte": "^3.2.0",
    "axios": "0.19.2",
    "bootstrap": "^5.1.3",
    "datatables.net": "^1.11.5",
    "datatables.net-dt": "^1.11.5",
    "immer": "3.2.0",
    "jwt-decode": "^3.1.2",
    "react": "16.14.0",
    "react-bootstrap": "^2.2.3",
    "react-data-table-component": "^7.5.0",
    "react-datepicker": "^4.7.0",
    "react-dom": "16.14.0",
    "react-icons": "^4.3.1",
    "react-redux": "7.2.2",
    "react-router-dom": "^6.3.0",
    "react-scripts": "3.4.4",
    "redux": "4.0.5",
    "redux-mock-store": "1.5.4",
    "redux-thunk": "2.3.0",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "2.0.3",
    "styled-components": "^5.3.5",
    "typescript": "^4.2.4"
  },
  "devDependencies": {
    "@types/jest": "24.0.13",
    "@types/node": "12.0.2",
    "@types/react": "17.0.0",
    "@types/react-dom": "17.0.0",
    "@types/react-router": "5.1.18",
    "@types/react-router-dom": "^5.3.3",
    "@types/react-router-redux": "5.0.18",
    "@types/uuid": "^8.3.4",
    "braces": "3.0.2",
    "husky": "2.7.0",
    "lint-staged": "9.5.0",
    "micromatch": "4.0.2",
    "node-forge": "0.10.0",
    "npm-force-resolutions": "0.0.3",
    "prettier": "1.17.1",
    "typescript": "^4.2.4",
    "websocket-driver": "0.7.4"
  },
  "resolutions": {
    "mixin-deep": "2.0.1",
    "websocket-driver": "0.7.4",
    "node-forge": "0.10.0"
  },
  "scripts": {
    "preinstall": "npx npm-force-resolutions",
    "start": "react-scripts start",
    "start:ci": "CI=true BROWSER=none PORT=3000 react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "test:coverage": "set CI=true && react-scripts test --coverage",
    "eject": "react-scripts eject"
  },
  "jest": {
    "collectCoverageFrom": [
      "**/*.{js,jsx,tsx,ts}",
      "!**/node_modules/**",
      "!**/coverage/**",
      "!**/src/components/containers/__tests__/**"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "useBuiltIns": "entry"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}": [
      "prettier --single-quote --write",
      "git add"
    ]
  }
}

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment] 2022-05-31 19:22
This looks like a duplicate of #4352. Can you please try to check `semantic-ui-react@2.1.3`?

**Closed as completed by layershifter** 2022-05-31 19:22 UTC

**Comment by leonardopn** [comment] 2022-05-31 19:36
Same problem with version `semantic-ui-react@2.1.3`. Other components have similar problems like Popop, Header, Icon, Modal.Actions and etc.

**Comment by leonardopn** [comment] 2022-05-31 19:42
I recommend remove `@type/react` and `@types/react-dom`  and upgrading to `semantic-ui-react@2.1.3`

I'm using react version `react@17.0.2` and by removing these types explicitly from my `package.json`, the problems with semantic are gone
