### ISSUE TITLE
<Grid> is not using 'columns' prop, stays at 16

### ISSUE THREAD

**Issue by danatemple** [Semantic-Org/Semantic-UI-React#4127] opened 2020-12-13 11:33 UTC
## Bug Report

When changing the number of columns on a <Grid> to other than sixteen, behavior is still as if the value is sixteen.

<Grid columns='12'>
  <Grid.Column width='4' />
  <Grid.Column width='4' />
  <Grid.Column width='4' />
</Grid>

I expect three columns filling the width of the grid. It actually looks like this (grid in blue, columns in red).
See also the CodeSandbox demo.

![image](https://user-images.githubusercontent.com/11148387/102010499-b2163a80-3d3e-11eb-8908-9b628b4eef56.png)

### Version

2.0.1 (and all versions back to 0.86 as far as I can see)

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-fs5e1?file=/index.js

**Comment by layershifter** [comment] 2020-12-13 12:10
Duplicate of #1886.

---

This behavior is expected, please check following comments as they might be helpful:
https://github.com/Semantic-Org/Semantic-UI-React/issues/1886#issuecomment-317014011
https://github.com/Semantic-Org/Semantic-UI-React/issues/1886#issuecomment-325233848

For you use case I suggest to use:

```tsx
<Grid columns={3} />
```

https://codesandbox.io/s/semantic-ui-react-forked-6ur5z?file=/index.js

SUI docs can also clarify how CSS part works:
https://semantic-ui.com/collections/grid.html

**Closed as completed by layershifter** 2020-12-13 12:10 UTC
Labels: duplicate

**Comment by danatemple** [comment] 2020-12-13 12:16
@layershifter 
Am I not doing exactly as levithomasen says in #1886 in the comment you refer to?

    <Grid columns='12'>
      <Grid.Column width='4' />
      <Grid.Column width='4' />
      <Grid.Column width='4' />
    </Grid>

It is not working. My actual target use case is to have column widths 2,3,3,3 (i.e. 11 in total and not equal) but I thought as the very simple example from #1886 was still not working, I'd report that.

https://github.com/Semantic-Org/Semantic-UI-React/issues/1886#issuecomment-325233848

**Comment by layershifter** [comment] 2020-12-13 12:41
> @layershifter
> Am I not doing exactly as levithomasen says in #1886 in the comment you refer to?

You're right, that reply contains a wrong snippet. I updated it.

---

```
12 | 2 3 3 3
// is equal in percents
12 | 16.6% 25% 25% 25%
```

And it's not translates well to 16 columns as:
- 2 will be 12.5%
- 3 will be 18.75%

(_hope that I count it correctly 😸_ )

Without custom CSS using 3/4/4/4 will be the closest:

```tsx
<Grid>
  <Grid.Column width="3" />
  <Grid.Column width="4" />
  <Grid.Column width="4" />
  <Grid.Column width="4" />
</Grid>
```

However, you can tweak width manually for an exact match:

```tsx
<Grid>
  <Grid.Column style={{ width: "12.5%" }} />
  <Grid.Column width="4" />
  <Grid.Column width="4" />
  <Grid.Column width="4" />
</Grid>
```

https://codesandbox.io/s/semantic-ui-react-forked-u2315?file=/index.js

**Comment by danatemple** [comment] 2020-12-13 16:23
@layershifter thanks for explaining.

So conclusion is that **only columns='16' is supported** really?

If setting Grid 'columns' to anything other than 16, you cannot use the 'width' property on the columns, but have to either have equal width columns, or style their width manually. Is that correct?

It might be worth a 1-line clarification in the docs
https://react.semantic-ui.com/collections/grid/#variations-column-count
