### ISSUE TITLE
modal not work properly

### ISSUE THREAD

**Issue by MAmin233** [Semantic-Org/Semantic-UI-React#2700] opened 2018-04-03 09:14 UTC
modal not work properly

i am using semantic-ui-react for my react app and using gulp to generate the css files ( semantic css version 2.3.1 )  but when i use modal in my app the modal not load on the center of the page and it looks so bad and no animation shows while loading the modal 

but in the react.semantic-ui.com  the modal example looks good but it doesn't have animation too 
but the main problem isn't the animation and the problem is that modal doesn't load on the center of the page and it shows on top of the page and some part of modal is above the page and i can't see the modal completely

**Comment by davidhenley** [comment] 2018-04-03 10:36
Duplicate of #2550

**Closed as completed** 2018-04-03 16:24 UTC
Labels: triage
