### ISSUE TITLE
Popover component stays open when clicking another popover

### ISSUE THREAD

**Issue by austinfox** [Semantic-Org/Semantic-UI-React#2096] opened 2017-09-21 01:00 UTC
### Steps
1.) Trigger a popover that opens on 'click'
2.) Trigger another popover that also opens on 'click'

### Expected Result
The first popover closes and the second one opens

### Actual Result
Both popovers stay open
*notice:* It takes two clicks outside of the popovers to dismiss both of them

### Version
0.7.3

### Testcase
https://react.semantic-ui.com/modules/popup

The docs makes this perfectly obvious. Click on one of the popovers that triggers on 'click' and then another that is also triggered on 'click'

**Comment by layershifter** [comment] 2017-09-21 06:50
@austinfox you're right about `Portal`, however, it's duplicate of #2075.

**Closed as completed by layershifter** 2017-09-21 06:50 UTC
Labels: duplicate
