### ISSUE TITLE
Failed prop type: Invalid prop `name` of value `discord` supplied to `Icon`.

### ISSUE THREAD

**Issue by kevflynn** [Semantic-Org/Semantic-UI-React#2753] opened 2018-04-30 21:42 UTC
### Steps
Render Icon component with name="discord"

### Expected Result
Renders Discord icon with no error

### Actual Result
Renders Discord icon with invalid prop value error.

### Version
0.79.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment] 2018-05-01 03:25
Duplicate of #2550

**Closed as completed by brianespinosa** 2018-05-01 03:25 UTC
Labels: duplicate
