### ISSUE TITLE
wrong selected option with Search Selection

### ISSUE THREAD

**Issue by floverdevel** [Semantic-Org/Semantic-UI-React#3560] opened 2019-04-09 16:16 UTC
### Steps
- go to https://react.semantic-ui.com/modules/dropdown/#types-search-selection to use the *Search Selection* dropdown
- click on the dropdown to open it
- the list of all options appears
- type the letter "c"
- the list is now filtered with only the options containing the letter "c"
- - Americana
- - Caicos Island
- - Cambodia
- - Cameroon
- - Canada
- choose the 3rd options (Cambodia)
- the dropdown closes
- the text is "Cambodia"
- click again on the dropdown to open it
- the list of all options appears

### Expected Result
- selected text is "Cambodia"
- the list is scrolled to "Cambodia"

### Actual Result 💣
- selected text is the 3rd visible option (Albania)
- the list is not scrolled to "Cambodia"
- even worse is that clicking outside the dropdown changes the value to "Albania" but this is probably because the "selectOnBlur" props is true by default

### Version
0.86.0

**Comment by mihai-dinculescu** [comment] 2019-04-23 11:01
I can confirm the bug. It sounds like a biggie. I'll try and have a look at it.

**Comment by mihai-dinculescu** [comment] 2019-04-23 17:43
The issue is caused by `setSelectedIndex(...)` being called after `clearSearchQuery()`, but running before the search query is updated in the state.

The easy fix to to call `setSelectedIndex(...)` in the `open(...)` function. Unless someone has a better idea...

**Comment by mihai-dinculescu** [comment] 2019-04-25 16:20
Duplicate of #3552.

**Closed as completed** 2019-04-25 16:19 UTC
Labels: duplicate
