### ISSUE TITLE
Search-in-menu dropdowns close when search input is focused (filtering items is impossible)

### ISSUE THREAD

**Issue by Dan1ve** [Semantic-Org/Semantic-UI-React#4160] opened 2021-02-26 13:42 UTC
## Bug Report

The examples for some dropdowns on the public website don't work as expected.
This affects both examples for the filter-in-menu dropdowns https://react.semantic-ui.com/modules/dropdown/#types-search-in-menu.

When you focus the input element to filter the dropdown items, the dropdown element closes itself. 
This means that you cannot use the filter functionality at all.

Here is a GIF showing the problem:

![semantic-ui-react](https://user-images.githubusercontent.com/7125814/109306278-3ad14c80-783f-11eb-85c3-7f0afa2214e4.gif)

(See also the test case sandbox)

### Steps
As mentioned above, simply 
- open a dropdown with a search menu 
- click the input field for filtering the dropdown items

### Expected Result
- I can type a filter text and the dropdown items are filtered accordingly
- Actually, I think it would be nice and more consistent if the input field was focused automatically when I open the dropdown

### Actual Result
- the dropdown closes itself

### Version
2.0.3 (assuming the website runs the latest version)

### Testcase

Minimal reproduction example: https://codesandbox.io/s/semantic-ui-react-forked-rn8kq

**Comment by phuoc-insignia** [comment] 2021-04-02 06:03
Please refer this https://github.com/Semantic-Org/Semantic-UI-React/issues/4045#issuecomment-680729907

**Comment by brianespinosa** [comment] 2021-04-05 19:13
Dupe of #1593 

Thank you @phuoc-insignia for referencing the workaround and conversations with additional context.

**Closed as completed by brianespinosa** 2021-04-05 19:13 UTC
Labels: duplicate
