### ISSUE TITLE
Loading Form.Button can't be set disabled

### ISSUE THREAD

**Issue by grigy** [Semantic-Org/Semantic-UI-React#1142] opened 2017-01-10 19:00 UTC
### Steps
Create disabled and loading form button.

### Expected Result
It should be a disabled button with loading indicator.

### Actual Result
It's not a disabled button.

### Version
0.63.5

### Testcase
http://codepen.io/grigy/pen/mRVmEz

**Comment by levithomason** [comment] 2017-01-11 19:57
This is actually a dupe of https://github.com/Semantic-Org/Semantic-UI-React/issues/1115.  Form field shorthand should pass along the `disabled` prop whereas they are consuming it.

Workaround, don't use the Form.Button shorthand:
http://codepen.io/levithomason/pen/wgGKpz
```jsx
      <Form>
        <Form.Field>
          <Button loading disabled>Button</Button>
        </Form.Field>
      </Form>
```

**Comment by levithomason** [comment] 2017-01-11 19:57
I should note, this will be fixed :)

**Closed as completed by levithomason** 2017-01-11 19:57 UTC
