### ISSUE TITLE
Popup - allow mouseEnter, mouseLeave delay to be set via props

### ISSUE THREAD

**Issue by bw2** [Semantic-Org/Semantic-UI-React#1163] opened 2017-01-15 01:44 UTC
Currently mouseEnter and mouseLeave delay values are hard-coded. 
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Popup/Popup.js#L264

It would be great if these could be set via popup props.

**Comment by levithomason** [comment] 2017-01-16 17:14
This is actually a bug.  All portal props (i.e. `mouseEnterDelay`, etc.) can be added to a Popup and it _should_ pass them through to the underlying Portal:

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Popup/Popup.js#L346

However, when I try this in the doc site editor, I cannot get it to work.  It seems the value is always overridden somehow.

### Fix

Currently, there is no visibility of this in the docs nor typings.  We should instead explicitly add all the portal props to the Popup's `propTypes` and typings.  Doing this will also change how the props are built-up and consumed.  This may in fact also resolve the bug.

**Comment by tarang9211** [comment] 2017-01-16 20:37
@levithomason this still open? i'd like to help out if so, with more info and knowledge of how to reproduce it!

**Comment by levithomason** [comment] 2017-01-17 19:43
I, unfortunately, don't have the bandwidth for a walkthrough, however, you can check out #1169 for more info on what needs to happen here.  I will be glad to offer PR review comments regarding what is missing or needs done, I just can't promise that I'll be able to also help craft the solutions.

**Comment by kasbah** [comment] 2017-02-23 17:11
This seems to be fixed in 0.66.0 but it's not documented. Works for me with `mouseLeaveDelay` and `mouseEnterDelay` props.

**Comment by levithomason** [comment] 2017-02-23 17:40
I've revamped a lot of Portal and Popup logic.  Confirming it was fixed in the latest release.

![http://g.recordit.co/tybYxhNGmo.gif](http://g.recordit.co/tybYxhNGmo.gif)

Closing this issue as we have #1169 for documenting missing props and behaviors.

**Closed as completed by levithomason** 2017-02-23 17:40 UTC
Labels: bug, help wanted, good first issue

**Comment by nfantone** [comment] 2018-02-24 22:01
@levithomason I tried this today and, while it seems to work (behaves like your GIF above), the `Popup` is still triggered by a _click_ event, even if setting `on="hover"`.

![znybz6ew6x](https://user-images.githubusercontent.com/476069/36635507-17390bf2-19ae-11e8-8fcb-8d745b3a7711.gif)

(Note that `mouseEnterDelay` is set to `10s`).

---

**EDIT**: Created #2583.
