### ISSUE TITLE
Popup doesn't stay open when hovering

### ISSUE THREAD

**Issue by kirillku** [Semantic-Org/Semantic-UI-React#3297] opened 2018-11-23 12:39 UTC
## Bug Report
Seems like `hoverable` prop on `Popup` doesn't work anymore. Or it works really strange.

### Steps
Can be reproduced with [variations-flowing example](https://react.semantic-ui.com/modules/popup/#variations-flowing). Sometimes I can hover one button inside popup and it will stay open, but I'm not able to hover all of them one after another.

![demo](https://user-images.githubusercontent.com/3331461/48943807-1635ee00-ef2d-11e8-978f-602601e8ec7a.gif)

### Expected Result
Popup is open when its content is hovered.

### Actual Result
Most of the times it just closes, sometimes it's open a bit longer when you hover some specific place, but then when you start moving your mouse, it closes.

### Version
0.83.0

**Comment by Grisu118** [comment] 2018-11-23 15:02
Duplicate of #3239

**Closed as completed** 2018-11-25 09:30 UTC
Labels: duplicate
