### ISSUE TITLE
Dropdown fires onChange when navigating through the options with keyboard cursor (UP and DOWN) instead of when you actually select the desired option (RETURN)

### ISSUE THREAD

**Issue by rigobauer** [Semantic-Org/Semantic-UI-React#3198] opened 2018-10-07 06:59 UTC
### Steps
You need a Dropdown with search and selection enabled. Then...
1. Click in the dropdown and make a search.
2. Set an onChange function that just do `console.log('onChange executed')`.
3. Click on the Dropdown to open the options.
4. Press arrow keys up and down on the keyboard to start moving over the options.
5. You'll see that everytime you press the key, onChange is fired (you'll see the console.log message)

With current behavior, if your application fires some code when you select an option (loading another dropdown, showing/hiding something, etc.), that code is going to be executed when you're moving through the options. This can be problematic, because maybe you're reseting some state, so you can´t recover that data.

### Expected Result
onChange only should be fired when you actually select one option pressing ENTER.

### Actual Result
onChange is fired when you move through the options just to find the one you want to select. So, onChange is executed even if you don't change your selection.

### Version
0.82.5

### Testcase
https://codesandbox.io/s/jn76nn5z5v

**Comment by quiqueg** [comment] 2019-03-04 04:41
@rigobauer This is the default behavior by design. You can get the behavior you are expecting by setting the `selectOnNavigation` prop to `false`. https://react.semantic-ui.com/modules/dropdown/#usage-select-on-navigation

**Comment by Adoroam** [comment] 2019-05-16 18:24
> @rigobauer This is the default behavior by design. You can get the behavior you are expecting by setting the `selectOnNavigation` prop to `false`. https://react.semantic-ui.com/modules/dropdown/#usage-select-on-navigation

I was looking to solve another issue but decided that this would be nice to use. I was unable to get the `selectOnNavigation` prop to work as described with any `Dropdown`s or `Select`s, `Form` or otherwise.

**Comment by alqh** [comment] 2019-06-12 21:05
I had it with two flags - selectOnBlur: false,  selectOnNavigation: false for it not to select unless the user clicks the option or hits enter on the option

**Comment by brianespinosa** [comment] 2020-07-29 17:25
> @rigobauer This is the default behavior by design. You can get the behavior you are expecting by setting the `selectOnNavigation` prop to `false`. https://react.semantic-ui.com/modules/dropdown/#usage-select-on-navigation

Closing as this has been addressed.

**Closed as completed by brianespinosa** 2020-07-29 17:25 UTC
Labels: invalid
