### ISSUE TITLE
docs - menu dropdown issue

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-React#776] opened 2016-10-31 09:43 UTC
in the docs, clicking the on Categories toggles the dropdown once. Then it doesn't work again unless you refresh the page.

![image](https://cloud.githubusercontent.com/assets/957271/19849257/771bb43c-9f95-11e6-8859-a56010485ef5.png)

**Comment by layershifter** [comment] 2016-10-31 10:35
Looks like #659

**Comment by Maxhodges** [comment] 2016-10-31 11:01
when you click Categories in this demo, you can open and close the dropdown **once**. But then you cannot get it to reopen again, unless you refresh the page.

**Comment by levithomason** [comment] 2016-10-31 18:26
@layershifter is correct, after the error is thrown the Dropdown stops working.  This is a duplicate of #659.

The console error:

```
app.6ff4071….js:6326 Uncaught TypeError: a._dropdown.blur is not a function(…)
```

**Closed as completed** 2016-11-22 20:51 UTC
Labels: duplicate

**Comment by levithomason** [comment] 2017-01-24 21:03
Released in `semantic-ui-react@0.64.4`.
