### ISSUE TITLE
Modal Scrolling

### ISSUE THREAD

**Issue by THEJean-Kevin** [Semantic-Org/Semantic-UI-React#3817] opened 2019-10-24 19:11 UTC
### Steps
1. Create a modal
2. Add some important Element

I found the probleme but don't know how to resolve this
scolling class was added to the body if I remove it I resolve the probleme
[https://i.gyazo.com/c3321fde03b7b837760373b508d7231c.png](https://i.gyazo.com/c3321fde03b7b837760373b508d7231c.png)

### Expected Result
[https://i.gyazo.com/20a8b64a4738a8654f5fea3384c80620.png](https://i.gyazo.com/20a8b64a4738a8654f5fea3384c80620.png)
Without scrolling class on body
[https://i.gyazo.com/2de692077cba23a6029d871a9ed5a535.png](https://i.gyazo.com/2de692077cba23a6029d871a9ed5a535.png)

### Actual Result
[https://i.gyazo.com/20a8b64a4738a8654f5fea3384c80620.png](http://i.gyazo.com/09b2171ac0c2a58dd2ee82fb5bde8163.png)
[https://i.gyazo.com/01d28e0449d8a671f82a390c5f1e1d99.png](https://i.gyazo.com/01d28e0449d8a671f82a390c5f1e1d99.png)

### Version
    "semantic-ui-react": "0.88.1"

### Testcase
No bug on codeSandBox
https://codesandbox.io/s/semantic-ui-react-jmrok?fontsize=14

P.S Sry for my english I try to do my best

**Comment by brianespinosa** [comment] 2020-07-28 18:31
@THEJean-Kevin thank you for your report.

If this is not reproducible in a Codesandbox example, that is a good way to tell that something else is happening differently inside of your working environment. That could be coming from another library adding that class, it could be that your Codesandbox example is implemented in a different way than your working repository, etc.

It is also a good way for us to isolate the problem and see if we can reproduce the issue without any of the conflicts that might happen in a codebase with lots of variables.

Since this is not reproducible in your test case, I am going to close this issue. I recommend asking your question on Stackoverflow and sharing some information about other things happening in your environment that might be introducing those scenarios.

**Closed as completed by brianespinosa** 2020-07-28 18:31 UTC
Labels: question
