### ISSUE TITLE
Popups closes when an item is removed from a nested multi dropdown component.

### ISSUE THREAD

**Issue by marbemac** [Semantic-Org/Semantic-UI-React#1910] opened 2017-07-30 18:51 UTC
note that this might be related (or a duplicate of) #1580 

### Steps

1. Use multi dropdown component inside of a hoverable popup component (sample code below).
2. Open popup, select some items in the dropdown component (this works fine).
3. Click the "x" on one of the dropdown item labels to remove it.
4. The removal happens fine, but the popup is closed.

```js
import React from 'react';
import { Button, Popup, Dropdown } from 'semantic-ui-react';

const options = [
  { key: 'angular', text: 'Angular', value: 'angular' },
  { key: 'css', text: 'CSS', value: 'css' },
  { key: 'design', text: 'Graphic Design', value: 'design' },
];

const PopupDropdownExample = () =>
  <Popup trigger={<Button content="Show Dropdown" />} on="click" position="top right">
    <Dropdown placeholder="Skills" fluid multiple selection options={options} />
  </Popup>;

export default PopupDropdownExample;
```

### Expected Result

Popups should not close when an item is removed from an embedded multi dropdown component.

### Actual Result

Popup is closed when multi item is removed from dropdown.

### Version

0.71.3

**Comment by layershifter** [comment] 2017-08-07 07:40
Yep, it's duplicate of #1580.

**Closed as completed by layershifter** 2017-08-07 07:40 UTC
Labels: duplicate
