### ISSUE TITLE
Warning using Menu component in strict Mode

### ISSUE THREAD

**Issue by raphaelpinel** [Semantic-Org/Semantic-UI-React#3936] opened 2020-04-21 09:18 UTC
### Steps
Create a fresh react application with typescript template
`npx create-react-app testProject --template typescript` (in my case React 16.13.1)

Use `<Menu>` component

### Expected Result
No warning in JS console

### Actual Result
in chrome devTools console:
`Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code [...] Please update the following components: Menu`

### Version
0.88.2

**Comment by layershifter** [comment] 2020-06-24 07:24
A duplicate of #3919, for `Menu` will be solved with #3967.

**Closed as completed by layershifter** 2020-06-24 07:24 UTC
Labels: duplicate
