### ISSUE TITLE
Dropdown missing upward option

### ISSUE THREAD

**Issue by nodegin** [Semantic-Org/Semantic-UI-React#975] opened 2016-12-01 22:51 UTC
I found that Semantic-Org/Semantic-UI#1146 added upward option for Dropdown.

However in the React version, it seems doesn't provide this option at all.

If my dropdown located in the bottom of the page, it will breaks the page layout.

I am using SUI React v0.61.4 currently.

Thanks for any help.

**Comment by levithomason** [comment] 2016-12-01 22:54
I believe this is a duplicate of #720.

**Closed as completed by levithomason** 2016-12-01 22:54 UTC
Labels: duplicate
