### ISSUE TITLE
Dropdown menu remains open

### ISSUE THREAD

**Issue by pfcodes** [Semantic-Org/Semantic-UI-React#3326] opened 2018-12-06 23:35 UTC
### Steps
Use the `Dropdown` component.

### Expected Result
The dropdown should close.

### Actual Result
The drop down menu remains open. Inspection of the source code shows that `display: block !important` makes up the value of the style attribute when the issue happens.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/26803762/49618182-890b8400-f985-11e8-919c-30fef06d4872.png">

### Version
0.83.0

**Comment by layershifter** [comment] 2018-12-10 08:39
@phlfvry can you please add more steps and codesandbox example? Then ping me and I will reopen the issue.

For now, I'm going to close it because it's not clear how we can reproduce it.

**Closed as completed by layershifter** 2018-12-10 08:39 UTC
Labels: invalid
