### ISSUE TITLE
Modal: scroll breaks if two are adjacent and of different lengths

### ISSUE THREAD

**Issue by katpas** [Semantic-Org/Semantic-UI-React#1979] opened 2017-08-17 14:10 UTC
This is probably related to #1157 but it's not just if you have a modal within a modal that this bug exists, having two in the same component causes the same issue. 

### Steps

1. Create a component which contains two Modals where one has content long enough to require a scroll and the other doesn't.

2. Open the longer modal and scroll. Close this Modal. 

3. Open the shorter modal. Close this Modal.

4. Open the longer modal. Scroll no longer works. 

### Expected Result

The longer modal should always be scrollable.

### Actual Result

The longer modal gets stuck if opened after the shorter modal is opened and closed. 

### Version
0.71.3

### Testcase

https://codepen.io/anon/pen/Ljerpm

**Comment by layershifter** [comment] 2017-08-25 07:16
@katpas Thanks for report! PR is coming.

**Comment by katpas** [comment] 2017-08-25 08:21
@layershifter great! Thank you.

**Comment by levithomason** [comment] 2017-08-28 08:49
This is actually a duplicate of #1157.  The typo fixed in #2004 is still needed, however, the core issue is that the `dimmable dimmed` classes are removed by the inner Modal on unmount and they are never restored by the outer modal.  This is because they are only added on mount.

I've opened #2010 to also handle dimmer classes in the RAF.  I've also tested it locally to confirm it is working.

**Closed as completed by levithomason** 2017-08-28 08:49 UTC
Labels: duplicate
