### ISSUE TITLE
Search results with custom render cannot display custom id

### ISSUE THREAD

**Issue by taniarascia** [Semantic-Org/Semantic-UI-React#3322] opened 2018-12-04 19:35 UTC
## Bug Report

Search results with custom render cannot display custom id. It seems that trying to use a custom `id` property will be overridden by 0 indexed results.

### Steps

Use `resultRenderer` on the `<Search />` component, with `id` as one of the values in your object.

```
resultRenderer = ({id, name}) => <p>{id}</p>
```

### Expected Result

`{id}` will return custom string.

### Actual Result

`{id}` returns `0` instead of a custom string.

**Comment by layershifter** [comment] 2018-12-05 08:19
I'm going to mark this as duplicate of #1141:
- this issue comes from [this line](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Search/Search.js#L557) and I don't see any option how this can be resolved
- you can use `_id` or any other name, but it will cause `propTypes` warning and will point you to #1141

---

General conclusion: `Search` component should be refactored to match our latest shorthand API ideas and resolve all long standing problems there.

General problem: I don't have time for this. The help in this direction is much appreciated.

**Closed as completed** 2018-12-10 08:42 UTC
Labels: duplicate
