### ISSUE TITLE
Dropdown as Menu.Item not reopen

### ISSUE THREAD

**Issue by alessiodionisi** [Semantic-Org/Semantic-UI-React#1117] opened 2017-01-04 10:34 UTC
Dropdown as Menu.Item not reopen

### Steps
1. Open the dropdown
2. Close the dropdown
3. The dropdown is stuck closed

### Expected Result
Dropdown close and reopen

### Actual Result
The dropdown closes but not reopen

### Version
0.63.4

### Testcase
http://codepen.io/anon/pen/BpaMJR

### Error
`Uncaught TypeError: _this._dropdown.blur is not a function`

I will make a pull request with fixed dropdown

**Comment by layershifter** [comment] 2017-01-10 16:51
Duplicate of #659.

**Closed as completed by layershifter** 2017-01-10 16:51 UTC
Labels: duplicate

**Comment by levithomason** [comment] 2017-01-24 21:03
Released in `semantic-ui-react@0.64.4`.
