### ISSUE TITLE
Portal onClose event prematurely fires on release 0.83.0 but not on 0.82.5

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#3299] opened 2018-11-23 17:30 UTC
## Bug Report
Portal onClose event prematurely fires on release 0.83.0 but not on 0.82.5

### Steps
Move mouse onto portal trigger and leave mouse on portal, where Portal is defined as. 
```
<Portal
   openOnTriggerMouseEnter
   closeOnTriggerMouseLeave
   closeOnPortalMouseLeave
    mouseLeaveDelay={150}
    onOpen={this.handleOpen}
    onClose={this.handleClose}
    trigger={
      <Button onClick={this.handleClick}>My Button</Button>
   }
>
   <ShowFilters />
</Portal>
```
### Expected Result
onOpen handler is called.

### Actual Result
onOpen handler is called, then onClose handler is called.

### Version
0.83.0

**Comment by layershifter** [comment] 2018-12-10 08:44
@leantide please provide a codesandbox example with minimal code.

This can be also duplicate of #3257, can you try the latest version?

**Comment by layershifter** [comment] 2019-01-02 12:06
Closing as I didn't receive any response. Will reopen after a feedback.

**Closed as completed by layershifter** 2019-01-02 12:06 UTC
Labels: needs author feedback
