### ISSUE TITLE
Popup content doesn't dissapear

### ISSUE THREAD

**Issue by a-kon** [Semantic-Org/Semantic-UI-React#3589] opened 2019-04-30 08:14 UTC
## Bug Report
Hi! I found a bug with the Popup component.

### Steps
If there are several triggers with 'hoverable' popups, the popup won't close when you quickly switch from one trigger to another.
But if you slowly drag the cursor from the first trigger to the empty space, wait for a second and then hover the second popup trigger  - the first popup will disappear.

### Expected Result
Hoverable popups close as expected

### Actual Result
If there are several triggers with 'hoverable' popups, the popup won't close when you quickly switch from one trigger to another.

### Version
0.86.0

### Testcase
1. v0.86.0 https://codesandbox.io/s/1rlow9mn27    (bug)
2. v0.85.0 https://codesandbox.io/s/98308720wy  (works fine)

The first (red) column contains hoverable popups.
The second (green) column contains non-hoverable popups.
The third (blue) column contains hoverable popups, but the second popup has a margin for the first popup content to disappear.

**Comment by layershifter** [comment] 2019-05-02 07:19
Duplicate of #3508, was fixed already, but it's not released yet.

**Closed as completed by layershifter** 2019-05-02 07:19 UTC
Labels: duplicate
